In [1]:
# Import all the required libraries

import pdfplumber
from pathlib import Path
import pandas as pd
from operator import itemgetter
import json
import tiktoken
import openai
import chromadb

### Read and process the PDF File

In [3]:
pdf_file = 'Principal-Sample-Life-Insurance-Policy.pdf'

In [16]:
# Open the PDF file and print the text
with pdfplumber.open(pdf_file) as pdf:
    
    # Extract text from the first page
    print('---------- First Page -----------')
    single_page = pdf.pages[0]
    print(single_page)
    
    print('---------- Seventh Page -----------')
    # Get one of the pages from the PDF and examine it
    single_page = pdf.pages[5]
    text = single_page.extract_text()
    print(text)
    
    print('---------- Tables -----------')
    # Extract tables from the first page
    tables = single_page.extract_tables()
    print(tables)

---------- First Page -----------
<Page:1>
---------- Seventh Page -----------
TABLE OF CONTENTS
PART I - DEFINITIONS
PART II - POLICY ADMINISTRATION
Section A – Contract
Entire Contract Article 1
Policy Changes Article 2
Policyholder Eligibility Requirements Article 3
Policy Incontestability Article 4
Individual Incontestability Article 5
Information to be Furnished Article 6
Certificates Article 7
Assignments Article 8
Dependent Rights Article 9
Policy Interpretation Article 10
Electronic Transactions Article 11
Section B – Premium
Payment Responsibility; Due Dates; Grace Period Article 1
Premium Rates Article 2
Premium Rate Changes Article 3
Premium Amount Article 4
Contributions from Members Article 5
Section C - Policy Termination
Failure to Pay Premium Article 1
Termination Rights of the Policyholder Article 2
Termination Rights of The Principal Article 3
Policyholder Responsibility to Members Article 4
Section D - Policy Renewal
Renewal Article 1
PART III - INDIVIDUAL REQUIREMENTS AND RIGHTS
This policy has been updated effective January 1, 2014
GC 6001 TABLE OF CONTENTS, PAGE 1
---------- Tables -----------
[]

In [18]:
# Function to check whether a word if present in a table for segregation of regular text and tables

def check_bboxes(word, table_bbox):
    # Check whether word is inside a table bbox.
    l = word['x0'], word['top'], word['x1'], word['bottom']
    r = table_bbox
    return l[0] > r[0] and l[1] > r[1] and l[2] < r[2] and l[3] < r[3]

#### Function to extract text from a PDF file.
- Declare a variable i to store the iteration of the loop that will help us store page numbers alongside the text
- Declare an empty list 'full_text' to store all the text files
- Use pdfplumber to open the pdf pages one by one
- Find the tables and their locations in the page
- Extract the text from the tables in the variable 'tables'
- Extract the regular words by calling the function check_bboxes() and checking whether words are present in the table or not
- Use the cluster_objects utility to cluster non-table and table words together so that they retain the same chronology as in the original PDF
- Declare an empty list 'lines' to store the page text
- If a text element in present in the cluster, append it to 'lines', else if a table element is present, append the table
- Append the page number and all lines to full_text, and increment 'i'
- When the function has iterated over all pages, return the 'full_text' list

In [25]:
def extract_text_from_pdf(pdf_file):
    i = 0
    full_text = []
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            page_no = f"Page {i+1}"
            text = page.extract_text()

            tables = page.find_tables()
            table_bboxes = [i.bbox for i in tables]
            tables = [{'table': i.extract(), 'top': i.bbox[1]} for i in tables]
            non_table_words = [word for word in page.extract_words() if not any(
                [check_bboxes(word, table_bbox) for table_bbox in table_bboxes])]
            lines = []

            for cluster in pdfplumber.utils.cluster_objects(non_table_words + tables, itemgetter('top'), tolerance=5):

                if 'text' in cluster[0]:
                    try:
                        lines.append(' '.join([i['text'] for i in cluster]))
                    except KeyError:
                        pass

                elif 'table' in cluster[0]:
                    lines.append(json.dumps(cluster[0]['table']))


            full_text.append([page_no, " ".join(lines)])
            i +=1

    return full_text

In [31]:
data = []

# Processing the PDF file
print(f"Processing... {pdf_file}")

# Call the function to extract the text from the PDF
extracted_text = extract_text_from_pdf(pdf_file)

# Convert the extracted list to a PDF, and add a column to store document names
extracted_text_df = pd.DataFrame(extracted_text, columns=['Page No.', 'Page_Text'])

# Append the extracted text and document name to the list
data.append(extracted_text_df)

# Print a message to indicate progress
print(f"Finished processing {pdf_file}")

# Print a message to indicate all PDFs have been processed
print("PDF have been processed.")

Processing... Principal-Sample-Life-Insurance-Policy.pdf
Finished processing Principal-Sample-Life-Insurance-Policy.pdf
PDF have been processed.

In [32]:
# print the text
data

[   Page No.                                          Page_Text
 0    Page 1  DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...
 1    Page 2                 This page left blank intentionally
 2    Page 3  POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...
 3    Page 4                 This page left blank intentionally
 4    Page 5  PRINCIPAL LIFE INSURANCE COMPANY (called The P...
 ..      ...                                                ...
 59  Page 60  I f a Dependent who was insured dies during th...
 60  Page 61  Section D - Claim Procedures Article 1 - Notic...
 61  Page 62  A claimant may request an appeal of a claim de...
 62  Page 63                 This page left blank intentionally
 63  Page 64  Principal Life Insurance Company Des Moines, I...

 [64 rows x 2 columns]]

In [35]:
# Concat the data
insurance_pdfs_data = pd.concat(data, ignore_index = True)

In [37]:
# Print Page No and Page_Text from the dataframe
insurance_pdfs_data

   Page No.                                          Page_Text
0    Page 1  DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...
1    Page 2                 This page left blank intentionally
2    Page 3  POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...
3    Page 4                 This page left blank intentionally
4    Page 5  PRINCIPAL LIFE INSURANCE COMPANY (called The P...
..      ...                                                ...
59  Page 60  I f a Dependent who was insured dies during th...
60  Page 61  Section D - Claim Procedures Article 1 - Notic...
61  Page 62  A claimant may request an appeal of a claim de...
62  Page 63                 This page left blank intentionally
63  Page 64  Principal Life Insurance Company Des Moines, I...

[64 rows x 2 columns]

In [39]:
# Store the metadata for each page in a separate column
insurance_pdfs_data['Metadata'] = insurance_pdfs_data.apply(lambda x: {'Page_No.': x['Page No.']}, axis=1)
insurance_pdfs_data

,Page No.,Page_Text,Metadata
0,Page 1,DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...,{'Page_No.': 'Page 1'}
1,Page 2,This page left blank intentionally,{'Page_No.': 'Page 2'}
2,Page 3,POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...,{'Page_No.': 'Page 3'}
3,Page 4,This page left blank intentionally,{'Page_No.': 'Page 4'}
4,Page 5,PRINCIPAL LIFE INSURANCE COMPANY (called The P...,{'Page_No.': 'Page 5'}
...,...,...,...
59,Page 60,I f a Dependent who was insured dies during th...,{'Page_No.': 'Page 60'}
60,Page 61,Section D - Claim Procedures Article 1 - Notic...,{'Page_No.': 'Page 61'}
61,Page 62,A claimant may request an appeal of a claim de...,{'Page_No.': 'Page 62'}
62,Page 63,This page left blank intentionally,{'Page_No.': 'Page 63'}
63,Page 64,"Principal Life Insurance Company Des Moines, I...",{'Page_No.': 'Page 64'}

In [41]:
# Check one of the extracted page texts to ensure that the text has been correctly read
insurance_pdfs_data.Page_Text[2]

'POLICY RIDER GROUP INSURANCE POLICY NO: S655 COVERAGE: Life EMPLOYER: RHODE ISLAND JOHN DOE Effective on the later of the Date of Issue of this Group Policy or March 1, 2005, the following will apply to your Policy: From time to time The Principal may offer or provide certain employer groups who apply for coverage with The Principal a Financial Services Hotline and Grief Support Services or any other value added service for the employees of that employer group. In addition, The Principal may arrange for third party service providers (i.e., optometrists, health clubs), to provide discounted goods and services to those employer groups who apply for coverage with The Principal or who become insureds/enrollees of The Principal. While The Principal has arranged these goods, services and/or third party provider discounts, the third party service providers are liable to the applicants/insureds/enrollees for the provision of such goods and/or services. The Principal is not responsible for the provision of such goods and/or services nor is it liable for the failure of the provision of the same. Further, The Principal is not liable to the applicants/insureds/enrollees for the negligent provision of such goods and/or services by the third party service providers. EXCEPT AS SPECIFICALLY DESCRIBED IN THIS RIDER, ALL OTHER BENEFITS AND PROVISIONS WILL BE AS DESCRIBED IN THE GROUP POLICY. PRINCIPAL LIFE INSURANCE COMPANY DES MOINES, IOWA 50392-0001 GC 806 VAL'

In [49]:
# Also check the length of all the texts as there might be some empty pages or pages with very few words that we can drop
insurance_pdfs_data['Text_Length'] = insurance_pdfs_data['Page_Text'].apply(lambda x: len(x.split(' ')))

In [51]:
# print the page length
insurance_pdfs_data['Text_Length']

0      30
1       5
2     230
3       5
4     110
     ...
59    285
60    418
61    322
62      5
63      8
Name: Text_Length, Length: 64, dtype: int64

In [53]:
# Print the dataframe
insurance_pdfs_data

,Page No.,Page_Text,Metadata,Text_Length
0,Page 1,DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...,{'Page_No.': 'Page 1'},30
1,Page 2,This page left blank intentionally,{'Page_No.': 'Page 2'},5
2,Page 3,POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...,{'Page_No.': 'Page 3'},230
3,Page 4,This page left blank intentionally,{'Page_No.': 'Page 4'},5
4,Page 5,PRINCIPAL LIFE INSURANCE COMPANY (called The P...,{'Page_No.': 'Page 5'},110
...,...,...,...,...
59,Page 60,I f a Dependent who was insured dies during th...,{'Page_No.': 'Page 60'},285
60,Page 61,Section D - Claim Procedures Article 1 - Notic...,{'Page_No.': 'Page 61'},418
61,Page 62,A claimant may request an appeal of a claim de...,{'Page_No.': 'Page 62'},322
62,Page 63,This page left blank intentionally,{'Page_No.': 'Page 63'},5
63,Page 64,"Principal Life Insurance Company Des Moines, I...",{'Page_No.': 'Page 64'},8

In [55]:
# Check the entire page's text
insurance_pdfs_data['Page_Text']

0     DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...
1                    This page left blank intentionally
2     POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...
3                    This page left blank intentionally
4     PRINCIPAL LIFE INSURANCE COMPANY (called The P...
                            ...
59    I f a Dependent who was insured dies during th...
60    Section D - Claim Procedures Article 1 - Notic...
61    A claimant may request an appeal of a claim de...
62                   This page left blank intentionally
63    Principal Life Insurance Company Des Moines, I...
Name: Page_Text, Length: 64, dtype: object

In [57]:
# Iterating over all page titles to create the final df with individual chunks
page_nos = insurance_pdfs_data["Page No."]
page_nos

0      Page 1
1      Page 2
2      Page 3
3      Page 4
4      Page 5
       ...
59    Page 60
60    Page 61
61    Page 62
62    Page 63
63    Page 64
Name: Page No., Length: 64, dtype: object

In [61]:
# Function to split text into fixed-size chunks
def split_text_into_chunks(text, chunk_size):
    chunks = []
    words = text.split()  # Split the text into words

    current_chunk = []  # Store words for the current chunk
    current_chunk_word_count = 0  # Count of words in the current chunk

    for word in words:
        if current_chunk_word_count + len(word) + 1 <= chunk_size:
            current_chunk.append(word)
            current_chunk_word_count += len(word) + 1
        else:
            chunks.append(' '.join(current_chunk))
            current_chunk = [word]
            current_chunk_word_count = len(word)

    if current_chunk:
        chunks.append(' '.join(current_chunk))

    return chunks## 3.  Generating Embeddings

In [63]:
def process_page(page_no):
    page = insurance_pdfs_data[insurance_pdfs_data['Page No.'] == page_no].Page_Text.values[0]
    metadata = insurance_pdfs_data[insurance_pdfs_data['Page No.'] == page_no].Metadata.values[0]

    if page is not None:
        # setting chunk size as 500
        chunk_size = 500
        text_chunks = split_text_into_chunks(page, chunk_size)

        # Creating a DataFrame to store the chunks, page title and page metadata
        data = {'Title': [], 'Chunk Text': [], 'Metadata': []}

        for index, chunk in enumerate(text_chunks):
            data['Title'].append(page_no)
            data['Chunk Text'].append(chunk)
            # adding chunk no as part of metadata
            metadata['Chunk_No.'] = index
            data['Metadata'].append(metadata)

        return pd.DataFrame(data)

In [65]:
# creating a dataframe after calling process
all_dfs = []
for page_no in page_nos:
    df = process_page(page_no)
    if df is not None:
        all_dfs.append(df)

fixed_chunk_df = pd.concat(all_dfs, ignore_index=True)
fixed_chunk_df

,Title,Chunk Text,Metadata
0,Page 1,DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...,"{'Page_No.': 'Page 1', 'Chunk_No.': 0}"
1,Page 2,This page left blank intentionally,"{'Page_No.': 'Page 2', 'Chunk_No.': 0}"
2,Page 3,POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...,"{'Page_No.': 'Page 3', 'Chunk_No.': 2}"
3,Page 3,arrange for third party service providers (i.e...,"{'Page_No.': 'Page 3', 'Chunk_No.': 2}"
4,Page 3,the provision of such goods and/or services no...,"{'Page_No.': 'Page 3', 'Chunk_No.': 2}"
...,...,...,...
226,Page 62,"requested additional information, The Principa...","{'Page_No.': 'Page 62', 'Chunk_No.': 3}"
227,Page 62,may have the Member or Dependent whose loss is...,"{'Page_No.': 'Page 62', 'Chunk_No.': 3}"
228,Page 62,proof of loss has been filed and before the ap...,"{'Page_No.': 'Page 62', 'Chunk_No.': 3}"
229,Page 63,This page left blank intentionally,"{'Page_No.': 'Page 63', 'Chunk_No.': 0}"
230,Page 64,"Principal Life Insurance Company Des Moines, I...","{'Page_No.': 'Page 64', 'Chunk_No.': 0}"

### Generating Embeddings

In [70]:
# Import the SentenceTransformer library
from sentence_transformers import SentenceTransformer
from sentence_transformers import util

WARNING:tensorflow:From C:\Users\ATANU\AppData\Roaming\Python\Python311\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [71]:
# Load the embedding model
model_name = "all-MiniLM-L6-v2"
embedder = SentenceTransformer(model_name)

In [72]:
# Function to generate embeddings for text
def generate_embeddings(texts):
    embeddings = embedder.encode(texts, convert_to_tensor=False)
    return embeddings

In [76]:
# Function to generate embedding on dataframe
def generate_embeddings_on_df(df):
  df['Embeddings'] = df['Chunk Text'].apply(lambda x: generate_embeddings([x])[0])

In [78]:
generate_embeddings_on_df(fixed_chunk_df)

In [79]:
# print the dataframe
fixed_chunk_df

,Title,Chunk Text,Metadata,Embeddings
0,Page 1,DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...,"{'Page_No.': 'Page 1', 'Chunk_No.': 0}","[-0.025921917, 0.047777507, 0.055857766, 0.042..."
1,Page 2,This page left blank intentionally,"{'Page_No.': 'Page 2', 'Chunk_No.': 0}","[0.029118957, 0.060574066, 0.04641531, 0.03779..."
2,Page 3,POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...,"{'Page_No.': 'Page 3', 'Chunk_No.': 2}","[-0.0645379, 0.04319714, -8.394773e-05, -0.004..."
3,Page 3,arrange for third party service providers (i.e...,"{'Page_No.': 'Page 3', 'Chunk_No.': 2}","[-0.10200987, -0.028467676, -0.020565087, -0.0..."
4,Page 3,the provision of such goods and/or services no...,"{'Page_No.': 'Page 3', 'Chunk_No.': 2}","[-0.090008385, 0.07658207, 0.0049276487, -0.08..."
...,...,...,...,...
226,Page 62,"requested additional information, The Principa...","{'Page_No.': 'Page 62', 'Chunk_No.': 3}","[-0.04767192, 0.11277702, 0.06906491, -0.05086..."
227,Page 62,may have the Member or Dependent whose loss is...,"{'Page_No.': 'Page 62', 'Chunk_No.': 3}","[-0.079419956, 0.14404444, 0.031876147, -0.065..."
228,Page 62,proof of loss has been filed and before the ap...,"{'Page_No.': 'Page 62', 'Chunk_No.': 3}","[-0.1420601, 0.12368375, 0.120924726, -0.01142..."
229,Page 63,This page left blank intentionally,"{'Page_No.': 'Page 63', 'Chunk_No.': 0}","[0.029118957, 0.060574066, 0.04641531, 0.03779..."
230,Page 64,"Principal Life Insurance Company Des Moines, I...","{'Page_No.': 'Page 64', 'Chunk_No.': 0}","[-0.07104545, 0.11729969, -0.021952959, -0.035..."

### Store Embeddings in ChromaDB

In [83]:
import chromadb

# Call PersistentClient()
client = chromadb.PersistentClient(path = '/ChromaDB_Data/')

In [85]:
# Create a collection to store the embeddings. Collections in Chroma are where you can store your embeddings, documents, and any additional metadata.
collection = client.get_or_create_collection(name="insurance-collection")

In [87]:
collection.add(
    embeddings = fixed_chunk_df['Embeddings'].to_list(),
    documents = fixed_chunk_df['Chunk Text'].to_list(),
    metadatas = fixed_chunk_df['Metadata'].to_list(),
    ids = [str(i) for i in range(0, len(fixed_chunk_df['Embeddings']))]
)

Add of existing embedding ID: 0
Add of existing embedding ID: 1
Add of existing embedding ID: 2
Add of existing embedding ID: 3
Add of existing embedding ID: 4
Add of existing embedding ID: 5
Add of existing embedding ID: 6
Add of existing embedding ID: 7
Add of existing embedding ID: 8
Add of existing embedding ID: 9
Add of existing embedding ID: 10
Add of existing embedding ID: 11
Add of existing embedding ID: 12
Add of existing embedding ID: 13
Add of existing embedding ID: 14
Add of existing embedding ID: 15
Add of existing embedding ID: 16
Add of existing embedding ID: 17
Add of existing embedding ID: 18
Add of existing embedding ID: 19
Add of existing embedding ID: 20
Add of existing embedding ID: 21
Add of existing embedding ID: 22
Add of existing embedding ID: 23
Add of existing embedding ID: 24
Add of existing embedding ID: 25
Add of existing embedding ID: 26
Add of existing embedding ID: 27
Add of existing embedding ID: 28
Add of existing embedding ID: 29
Add of existing embedding ID: 30
Add of existing embedding ID: 31
Add of existing embedding ID: 32
Add of existing embedding ID: 33
Add of existing embedding ID: 34
Add of existing embedding ID: 35
Add of existing embedding ID: 36
Add of existing embedding ID: 37
Add of existing embedding ID: 38
Add of existing embedding ID: 39
Add of existing embedding ID: 40
Add of existing embedding ID: 41
Add of existing embedding ID: 42
Add of existing embedding ID: 43
Add of existing embedding ID: 44
Add of existing embedding ID: 45
Add of existing embedding ID: 46
Add of existing embedding ID: 47
Add of existing embedding ID: 48
Add of existing embedding ID: 49
Add of existing embedding ID: 50
Add of existing embedding ID: 51
Add of existing embedding ID: 52
Add of existing embedding ID: 53
Add of existing embedding ID: 54
Add of existing embedding ID: 55
Add of existing embedding ID: 56
Add of existing embedding ID: 57
Add of existing embedding ID: 58
Add of existing embedding ID: 59
Add of existing embedding ID: 60
Add of existing embedding ID: 61
Add of existing embedding ID: 62
Add of existing embedding ID: 63
Add of existing embedding ID: 64
Add of existing embedding ID: 65
Add of existing embedding ID: 66
Add of existing embedding ID: 67
Add of existing embedding ID: 68
Add of existing embedding ID: 69
Add of existing embedding ID: 70
Add of existing embedding ID: 71
Add of existing embedding ID: 72
Add of existing embedding ID: 73
Add of existing embedding ID: 74
Add of existing embedding ID: 75
Add of existing embedding ID: 76
Add of existing embedding ID: 77
Add of existing embedding ID: 78
Add of existing embedding ID: 79
Add of existing embedding ID: 80
Add of existing embedding ID: 81
Add of existing embedding ID: 82
Add of existing embedding ID: 83
Add of existing embedding ID: 84
Add of existing embedding ID: 85
Add of existing embedding ID: 86
Add of existing embedding ID: 87
Add of existing embedding ID: 88
Add of existing embedding ID: 89
Add of existing embedding ID: 90
Add of existing embedding ID: 91
Add of existing embedding ID: 92
Add of existing embedding ID: 93
Add of existing embedding ID: 94
Add of existing embedding ID: 95
Add of existing embedding ID: 96
Add of existing embedding ID: 97
Add of existing embedding ID: 98
Add of existing embedding ID: 99
Add of existing embedding ID: 100
Add of existing embedding ID: 101
Add of existing embedding ID: 102
Add of existing embedding ID: 103
Add of existing embedding ID: 104
Add of existing embedding ID: 105
Add of existing embedding ID: 106
Add of existing embedding ID: 107
Add of existing embedding ID: 108
Add of existing embedding ID: 109
Add of existing embedding ID: 110
Add of existing embedding ID: 111
Add of existing embedding ID: 112
Add of existing embedding ID: 113
Add of existing embedding ID: 114
Add of existing embedding ID: 115
Add of existing embedding ID: 116
Add of existing embedding ID: 117
Add of existing embedding ID: 118
Add of existing embedding ID: 119
Add of existing embedding ID: 120
Add of existing embedding ID: 121
Add of existing embedding ID: 122
Add of existing embedding ID: 123
Add of existing embedding ID: 124
Add of existing embedding ID: 125
Add of existing embedding ID: 126
Add of existing embedding ID: 127
Add of existing embedding ID: 128
Add of existing embedding ID: 129
Add of existing embedding ID: 130
Add of existing embedding ID: 131
Add of existing embedding ID: 132
Add of existing embedding ID: 133
Add of existing embedding ID: 134
Add of existing embedding ID: 135
Add of existing embedding ID: 136
Add of existing embedding ID: 137
Add of existing embedding ID: 138
Add of existing embedding ID: 139
Add of existing embedding ID: 140
Add of existing embedding ID: 141
Add of existing embedding ID: 142
Add of existing embedding ID: 143
Add of existing embedding ID: 144
Add of existing embedding ID: 145
Add of existing embedding ID: 146
Add of existing embedding ID: 147
Add of existing embedding ID: 148
Add of existing embedding ID: 149
Add of existing embedding ID: 150
Add of existing embedding ID: 151
Add of existing embedding ID: 152
Add of existing embedding ID: 153
Add of existing embedding ID: 154
Add of existing embedding ID: 155
Add of existing embedding ID: 156
Add of existing embedding ID: 157
Add of existing embedding ID: 158
Add of existing embedding ID: 159
Add of existing embedding ID: 160
Add of existing embedding ID: 161
Add of existing embedding ID: 162
Add of existing embedding ID: 163
Add of existing embedding ID: 164
Add of existing embedding ID: 165
Add of existing embedding ID: 166
Add of existing embedding ID: 167
Add of existing embedding ID: 168
Add of existing embedding ID: 169
Add of existing embedding ID: 170
Add of existing embedding ID: 171
Add of existing embedding ID: 172
Add of existing embedding ID: 173
Add of existing embedding ID: 174
Add of existing embedding ID: 175
Add of existing embedding ID: 176
Add of existing embedding ID: 177
Add of existing embedding ID: 178
Add of existing embedding ID: 179
Add of existing embedding ID: 180
Add of existing embedding ID: 181
Add of existing embedding ID: 182
Add of existing embedding ID: 183
Add of existing embedding ID: 184
Add of existing embedding ID: 185
Add of existing embedding ID: 186
Add of existing embedding ID: 187
Add of existing embedding ID: 188
Add of existing embedding ID: 189
Add of existing embedding ID: 190
Add of existing embedding ID: 191
Add of existing embedding ID: 192
Add of existing embedding ID: 193
Add of existing embedding ID: 194
Add of existing embedding ID: 195
Add of existing embedding ID: 196
Add of existing embedding ID: 197
Add of existing embedding ID: 198
Add of existing embedding ID: 199
Add of existing embedding ID: 200
Add of existing embedding ID: 201
Add of existing embedding ID: 202
Add of existing embedding ID: 203
Add of existing embedding ID: 204
Add of existing embedding ID: 205
Add of existing embedding ID: 206
Add of existing embedding ID: 207
Add of existing embedding ID: 208
Add of existing embedding ID: 209
Add of existing embedding ID: 210
Add of existing embedding ID: 211
Add of existing embedding ID: 212
Add of existing embedding ID: 213
Add of existing embedding ID: 214
Add of existing embedding ID: 215
Add of existing embedding ID: 216
Add of existing embedding ID: 217
Add of existing embedding ID: 218
Add of existing embedding ID: 219
Add of existing embedding ID: 220
Add of existing embedding ID: 221
Add of existing embedding ID: 222
Add of existing embedding ID: 223
Add of existing embedding ID: 224
Add of existing embedding ID: 225
Add of existing embedding ID: 226
Add of existing embedding ID: 227
Add of existing embedding ID: 228
Add of existing embedding ID: 229
Add of existing embedding ID: 230
Insert of existing embedding ID: 0
Insert of existing embedding ID: 1
Insert of existing embedding ID: 2
Insert of existing embedding ID: 3
Insert of existing embedding ID: 4
Insert of existing embedding ID: 5
Insert of existing embedding ID: 6
Insert of existing embedding ID: 7
Insert of existing embedding ID: 8
Insert of existing embedding ID: 9
Insert of existing embedding ID: 10
Insert of existing embedding ID: 11
Insert of existing embedding ID: 12
Insert of existing embedding ID: 13
Insert of existing embedding ID: 14
Insert of existing embedding ID: 15
Insert of existing embedding ID: 16
Insert of existing embedding ID: 17
Insert of existing embedding ID: 18
Insert of existing embedding ID: 19
Insert of existing embedding ID: 20
Insert of existing embedding ID: 21
Insert of existing embedding ID: 22
Insert of existing embedding ID: 23
Insert of existing embedding ID: 24
Insert of existing embedding ID: 25
Insert of existing embedding ID: 26
Insert of existing embedding ID: 27
Insert of existing embedding ID: 28
Insert of existing embedding ID: 29
Insert of existing embedding ID: 30
Insert of existing embedding ID: 31
Insert of existing embedding ID: 32
Insert of existing embedding ID: 33
Insert of existing embedding ID: 34
Insert of existing embedding ID: 35
Insert of existing embedding ID: 36
Insert of existing embedding ID: 37
Insert of existing embedding ID: 38
Insert of existing embedding ID: 39
Insert of existing embedding ID: 40
Insert of existing embedding ID: 41
Insert of existing embedding ID: 42
Insert of existing embedding ID: 43
Insert of existing embedding ID: 44
Insert of existing embedding ID: 45
Insert of existing embedding ID: 46
Insert of existing embedding ID: 47
Insert of existing embedding ID: 48
Insert of existing embedding ID: 49
Insert of existing embedding ID: 50
Insert of existing embedding ID: 51
Insert of existing embedding ID: 52
Insert of existing embedding ID: 53
Insert of existing embedding ID: 54
Insert of existing embedding ID: 55
Insert of existing embedding ID: 56
Insert of existing embedding ID: 57
Insert of existing embedding ID: 58
Insert of existing embedding ID: 59
Insert of existing embedding ID: 60
Insert of existing embedding ID: 61
Insert of existing embedding ID: 62
Insert of existing embedding ID: 63
Insert of existing embedding ID: 64
Insert of existing embedding ID: 65
Insert of existing embedding ID: 66
Insert of existing embedding ID: 67
Insert of existing embedding ID: 68
Insert of existing embedding ID: 69
Insert of existing embedding ID: 70
Insert of existing embedding ID: 71
Insert of existing embedding ID: 72
Insert of existing embedding ID: 73
Insert of existing embedding ID: 74
Insert of existing embedding ID: 75
Insert of existing embedding ID: 76
Insert of existing embedding ID: 77
Insert of existing embedding ID: 78
Insert of existing embedding ID: 79
Insert of existing embedding ID: 80
Insert of existing embedding ID: 81
Insert of existing embedding ID: 82
Insert of existing embedding ID: 83
Insert of existing embedding ID: 84
Insert of existing embedding ID: 85
Insert of existing embedding ID: 86
Insert of existing embedding ID: 87
Insert of existing embedding ID: 88
Insert of existing embedding ID: 89
Insert of existing embedding ID: 90
Insert of existing embedding ID: 91
Insert of existing embedding ID: 92
Insert of existing embedding ID: 93
Insert of existing embedding ID: 94
Insert of existing embedding ID: 95
Insert of existing embedding ID: 96
Insert of existing embedding ID: 97
Insert of existing embedding ID: 98
Insert of existing embedding ID: 99
Insert of existing embedding ID: 100
Insert of existing embedding ID: 101
Insert of existing embedding ID: 102
Insert of existing embedding ID: 103
Insert of existing embedding ID: 104
Insert of existing embedding ID: 105
Insert of existing embedding ID: 106
Insert of existing embedding ID: 107
Insert of existing embedding ID: 108
Insert of existing embedding ID: 109
Insert of existing embedding ID: 110
Insert of existing embedding ID: 111
Insert of existing embedding ID: 112
Insert of existing embedding ID: 113
Insert of existing embedding ID: 114
Insert of existing embedding ID: 115
Insert of existing embedding ID: 116
Insert of existing embedding ID: 117
Insert of existing embedding ID: 118
Insert of existing embedding ID: 119
Insert of existing embedding ID: 120
Insert of existing embedding ID: 121
Insert of existing embedding ID: 122
Insert of existing embedding ID: 123
Insert of existing embedding ID: 124
Insert of existing embedding ID: 125
Insert of existing embedding ID: 126
Insert of existing embedding ID: 127
Insert of existing embedding ID: 128
Insert of existing embedding ID: 129
Insert of existing embedding ID: 130
Insert of existing embedding ID: 131
Insert of existing embedding ID: 132
Insert of existing embedding ID: 133
Insert of existing embedding ID: 134
Insert of existing embedding ID: 135
Insert of existing embedding ID: 136
Insert of existing embedding ID: 137
Insert of existing embedding ID: 138
Insert of existing embedding ID: 139
Insert of existing embedding ID: 140
Insert of existing embedding ID: 141
Insert of existing embedding ID: 142
Insert of existing embedding ID: 143
Insert of existing embedding ID: 144
Insert of existing embedding ID: 145
Insert of existing embedding ID: 146
Insert of existing embedding ID: 147
Insert of existing embedding ID: 148
Insert of existing embedding ID: 149
Insert of existing embedding ID: 150
Insert of existing embedding ID: 151
Insert of existing embedding ID: 152
Insert of existing embedding ID: 153
Insert of existing embedding ID: 154
Insert of existing embedding ID: 155
Insert of existing embedding ID: 156
Insert of existing embedding ID: 157
Insert of existing embedding ID: 158
Insert of existing embedding ID: 159
Insert of existing embedding ID: 160
Insert of existing embedding ID: 161
Insert of existing embedding ID: 162
Insert of existing embedding ID: 163
Insert of existing embedding ID: 164
Insert of existing embedding ID: 165
Insert of existing embedding ID: 166
Insert of existing embedding ID: 167
Insert of existing embedding ID: 168
Insert of existing embedding ID: 169
Insert of existing embedding ID: 170
Insert of existing embedding ID: 171
Insert of existing embedding ID: 172
Insert of existing embedding ID: 173
Insert of existing embedding ID: 174
Insert of existing embedding ID: 175
Insert of existing embedding ID: 176
Insert of existing embedding ID: 177
Insert of existing embedding ID: 178
Insert of existing embedding ID: 179
Insert of existing embedding ID: 180
Insert of existing embedding ID: 181
Insert of existing embedding ID: 182
Insert of existing embedding ID: 183
Insert of existing embedding ID: 184
Insert of existing embedding ID: 185
Insert of existing embedding ID: 186
Insert of existing embedding ID: 187
Insert of existing embedding ID: 188
Insert of existing embedding ID: 189
Insert of existing embedding ID: 190
Insert of existing embedding ID: 191
Insert of existing embedding ID: 192
Insert of existing embedding ID: 193
Insert of existing embedding ID: 194
Insert of existing embedding ID: 195
Insert of existing embedding ID: 196
Insert of existing embedding ID: 197
Insert of existing embedding ID: 198
Insert of existing embedding ID: 199
Insert of existing embedding ID: 200
Insert of existing embedding ID: 201
Insert of existing embedding ID: 202
Insert of existing embedding ID: 203
Insert of existing embedding ID: 204
Insert of existing embedding ID: 205
Insert of existing embedding ID: 206
Insert of existing embedding ID: 207
Insert of existing embedding ID: 208
Insert of existing embedding ID: 209
Insert of existing embedding ID: 210
Insert of existing embedding ID: 211
Insert of existing embedding ID: 212
Insert of existing embedding ID: 213
Insert of existing embedding ID: 214
Insert of existing embedding ID: 215
Insert of existing embedding ID: 216
Insert of existing embedding ID: 217
Insert of existing embedding ID: 218
Insert of existing embedding ID: 219
Insert of existing embedding ID: 220
Insert of existing embedding ID: 221
Insert of existing embedding ID: 222
Insert of existing embedding ID: 223
Insert of existing embedding ID: 224
Insert of existing embedding ID: 225
Insert of existing embedding ID: 226
Insert of existing embedding ID: 227
Insert of existing embedding ID: 228
Insert of existing embedding ID: 229
Insert of existing embedding ID: 230

In [89]:
# Get few of data by ids from collection
collection.get(
    ids = ['0','1','2'],
    include = ['embeddings', 'documents', 'metadatas']
)

{'ids': ['0', '1', '2'],
 'embeddings': array([[-2.59219166e-02,  4.77775075e-02,  5.58577664e-02, ...,
         -4.93265949e-02, -5.85114732e-02,  2.35519800e-02],
        [ 2.91189570e-02,  6.05740659e-02,  4.64153104e-02, ...,
          5.95401041e-02, -2.83836890e-02,  5.31937974e-03],
        [-6.45378977e-02,  4.31971401e-02, -8.39477289e-05, ...,
         -3.78734246e-02,  1.79674663e-02, -7.36598670e-03]]),
 'documents': ['DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/01/2014 711 HIGH STREET GEORGE RI 02903 GROUP POLICY FOR: RHODE ISLAND JOHN DOE ALL MEMBERS Group Member Life Insurance Print Date: 07/16/2014',
  'This page left blank intentionally',
  'POLICY RIDER GROUP INSURANCE POLICY NO: S655 COVERAGE: Life EMPLOYER: RHODE ISLAND JOHN DOE Effective on the later of the Date of Issue of this Group Policy or March 1, 2005, the following will apply to your Policy: From time to time The Principal may offer or provide certain employer groups who apply for coverage with The Principal a Financial Services Hotline and Grief Support Services or any other value added service for the employees of that employer group. In addition, The Principal may'],
 'uris': None,
 'data': None,
 'metadatas': [{'Chunk_No.': 0, 'Page_No.': 'Page 1'},
  {'Chunk_No.': 0, 'Page_No.': 'Page 2'},
  {'Chunk_No.': 2, 'Page_No.': 'Page 3'}],
 'included': [<IncludeEnum.embeddings: 'embeddings'>,
  <IncludeEnum.documents: 'documents'>,
  <IncludeEnum.metadatas: 'metadatas'>]}

In [91]:
# Create a cache collection
cache_collection = client.get_or_create_collection(name='insurance-collection-cache')

In [93]:
# peek few of elements from cache collection
cache_collection.peek()

{'ids': ['what is the life insurance coverage for disability',
  'what is the Proof of ADL Disability or Total Disability',
  'what is condition of deatht while not wearing Seat Belt'],
 'embeddings': array([[-0.07620075,  0.10754956, -0.04078717, ..., -0.02822857,
          0.08649307,  0.08005349],
        [-0.1126289 ,  0.05175915, -0.00465672, ...,  0.10451437,
          0.02804654,  0.03974168],
        [ 0.00892728,  0.09783429, -0.02448488, ..., -0.0406705 ,
         -0.00775244,  0.04245879]]),
 'documents': ['what is the life insurance coverage for disability',
  'what is the Proof of ADL Disability or Total Disability',
  'what is condition of deatht while not wearing Seat Belt'],
 'uris': None,
 'data': None,
 'metadatas': [{'distances0': '0.7124123573303223',
   'distances1': '0.8027515411376953',
   'distances2': '0.8602005839347839',
   'distances3': '0.8729649186134338',
   'distances4': '0.8979799747467041',
   'distances5': '0.9084634184837341',
   'distances6': '0.9102334976196289',
   'distances7': '0.9125920534133911',
   'documents0': 'Member Life Insurance or Coverage During Disability terminates under this Group Policy. This policy has been updated effective January 1, 2014 PART III - INDIVIDUAL REQUIREMENTS AND RIGHTS GC 6011 Section F - Individual Purchase Rights, Page 1',
   'documents1': "Payment of benefits will be subject to the Beneficiary and Facility of Payment provisions of this PART IV, Section A. Article 6 - Member Life Insurance - Coverage During Disability A Member may be eligible to continue his or her Member Life and Member Accidental Death and Dismemberment Insurance and Dependent Life Insurance coverage during the Member's ADL Disability or Total Disability. a. Coverage Qualification To be qualified for Coverage During Disability, a Member must: (1) become ADL",
   'documents2': 'any Accelerated Benefit payment as described in PART IV, Section A, Article 7. Article 2 - Dependent Life Insurance a. Individual Policy If a Dependent qualifies and makes timely application, he or she may purchase an individual policy of life insurance under these terms: (1) The Dependent will not be required to submit Proof of Good Health. (2) The policy will be for life insurance only. No disability or other benefits will be included. (3) The policy will be on one of the forms, other than',
   'documents3': "Dependent's Life Insurance terminates because the Member's Coverage During Disability as described in PART IV, Section A, ceases because Total Disability ends and the Member does not return to Active Work within 31 days ; or (6) the Dependent's Life Insurance terminates because the Member's Accelerated Benefits Premium Waiver Period as described in PART IV, Section A, ceases and the Member does not qualify for Coverage During Disability. c. Application/Effective Date Notice of the individual",
   'documents4': 'disability that: (1) results from willful self-injury or self-destruction, while sane or insane; or (2) results from war or act of war; or (3) results from voluntary participation in an assault, felony, criminal activity, insurrection, or riot. Article 7 - Accelerated Benefits a. Accelerated Benefits Qualification To be qualified for an Accelerated Benefit payment, a Member must: (1) be Terminally Ill and insured for a Member Life Insurance benefit of at least $10,000; and (2) send a request for',
   'documents5': 'be the Coverage During Disability benefit in force on the date Total Disability ceases, less any individual policy amount purchased earlier under this Article 1, and less any Accelerated Benefit payment as described in PART IV, Section A, Article 7. (4) If termination is as described in b. (4) above, the maximum amount will be the Member Life Insurance benefit in force on the date the Member ceases Active Work, less any individual policy amount purchased earlier under this Article 1, and less',
   'documents6': 'Total Disability began. Failure to give Written proof within the time specified will not invalidate or reduce any claim if Written proof is given as soon as reasonably possible. Further, if a death benefit is paid under this section of the Group Policy, it will be in place of all other Member Life Insurance benefits provided under this Group Policy. f. Termination (Premium Waiver) This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance,',
   'documents7': 'terms of the Prior Policy, to have their premiums waived due to ADL Disability or Total Disability. NOTE: When insurance under this Group Policy replaces coverage under a Prior Policy and the Active Work requirement is waived, any benefits payable will be the lesser of the Scheduled Benefit of this Group Policy or the amount that would have been paid by the Prior Policy had it remained in force. b. Effective Date for Initial Insurance When Proof of Good Health is Required This policy has been',
   'ids0': '143',
   'ids1': '171',
   'ids2': '147',
   'ids3': '151',
   'ids4': '183',
   'ids5': '146',
   'ids6': '180',
   'ids7': '85',
   'included0': 'd',
   'included1': 'i',
   'included2': 's',
   'included3': 't',
   'included4': 'a',
   'included5': 'n',
   'included6': 'c',
   'included7': 'e',
   'metadatas0': "{'Chunk_No.': 4, 'Page_No.': 'Page 42'}",
   'metadatas1': "{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",
   'metadatas2': "{'Chunk_No.': 4, 'Page_No.': 'Page 43'}",
   'metadatas3': "{'Chunk_No.': 4, 'Page_No.': 'Page 44'}",
   'metadatas4': "{'Chunk_No.': 3, 'Page_No.': 'Page 51'}",
   'metadatas5': "{'Chunk_No.': 4, 'Page_No.': 'Page 43'}",
   'metadatas6': "{'Chunk_No.': 5, 'Page_No.': 'Page 50'}",
   'metadatas7': "{'Chunk_No.': 4, 'Page_No.': 'Page 28'}"},
  {'distances0': '0.6475231647491455',
   'distances1': '0.6827042102813721',
   'distances2': '0.7083491086959839',
   'distances3': '0.7096874713897705',
   'distances4': '0.8478822708129883',
   'distances5': '0.8719554543495178',
   'distances6': '0.8909155130386353',
   'distances7': '0.9010810852050781',
   'documents0': 'Disabled or Totally Disabled while insured for Member Life Insurance; and (2) become ADL Disabled or Totally Disabled prior to the attainment of age 60; and (3) remain ADL Disabled or Totally Disabled continuously; and (4) be under the regular care and attendance of a Physician; and (5) send proof of ADL Disability or Total Disability to The Principal when required; and (6) submit to Medical Examinations or Evaluations when required; and (7) return to The Principal, without claim, any individual',
   'documents1': 'The Principal has received first proof, then final proof must be sent within one year of the date ADL Disability or Total Disability began. c. Medical Examinations and Evaluations This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance, Page 4',
   'documents2': 'The Principal may require that a ADL Disabled or Totally Disabled Member be examined by a Physician or undergo an evaluation, at reasonable intervals, during the course of a claim. After ADL Disability or Total Disability has continued two years from the date first proof of ADL Disability or Total Disability is received, examinations or evaluations may not be required more than once each year. The Principal will pay for these examinations and evaluations and will choose the Physician or',
   'documents3': 'policy issued under his or her Individual Purchase Rights as described in PART III, Section F, Article 1. Upon return of such policy, The Principal will refund premiums paid, less dividends and less any outstanding policy loan balance. b. Proof of ADL Disability or Total Disability Written proof of ADL Disability or Total Disability must be sent to The Principal within one year of the date ADL Disability or Total Disability begins. Further proof that ADL Disability or Total Disability has not',
   'documents4': "Disability is in force, The Principal will pay the Member's beneficiary the Member Life Insurance benefit amount that would have been paid had the Member remained insured under the Schedule of Insurance in force on the date Total Disability began. Such benefit shall be subject to any reduction provided under the Schedule of Insurance. However, NO BENEFIT WILL BE PAID if Written proof of ADL Disability or Total Disability is not sent to The Principal within one year of the date ADL Disability or",
   'documents5': "Payment of benefits will be subject to the Beneficiary and Facility of Payment provisions of this PART IV, Section A. Article 6 - Member Life Insurance - Coverage During Disability A Member may be eligible to continue his or her Member Life and Member Accidental Death and Dismemberment Insurance and Dependent Life Insurance coverage during the Member's ADL Disability or Total Disability. a. Coverage Qualification To be qualified for Coverage During Disability, a Member must: (1) become ADL",
   'documents6': 'terms of the Prior Policy, to have their premiums waived due to ADL Disability or Total Disability. NOTE: When insurance under this Group Policy replaces coverage under a Prior Policy and the Active Work requirement is waived, any benefits payable will be the lesser of the Scheduled Benefit of this Group Policy or the amount that would have been paid by the Prior Policy had it remained in force. b. Effective Date for Initial Insurance When Proof of Good Health is Required This policy has been',
   'documents7': 'ended must be sent when The Principal requires. After ADL Disability or Total Disability has continued for two years from the date the first proof is received, The Principal may not ask for further proof more than once each year. If the Member dies while ADL Disabled or Totally Disabled, final proof that ADL Disability or Total Disability continued to the date of death must be sent to The Principal. If death occurs within one year of the start of ADL Disability or Total Disability, but before',
   'ids0': '172',
   'ids1': '175',
   'ids2': '176',
   'ids3': '173',
   'ids4': '179',
   'ids5': '171',
   'ids6': '85',
   'ids7': '174',
   'included0': 'd',
   'included1': 'i',
   'included2': 's',
   'included3': 't',
   'included4': 'a',
   'included5': 'n',
   'included6': 'c',
   'included7': 'e',
   'metadatas0': "{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",
   'metadatas1': "{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",
   'metadatas2': "{'Chunk_No.': 5, 'Page_No.': 'Page 50'}",
   'metadatas3': "{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",
   'metadatas4': "{'Chunk_No.': 5, 'Page_No.': 'Page 50'}",
   'metadatas5': "{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",
   'metadatas6': "{'Chunk_No.': 4, 'Page_No.': 'Page 28'}",
   'metadatas7': "{'Chunk_No.': 4, 'Page_No.': 'Page 49'}"},
  {'distances0': '0.8488266316097228',
   'distances1': '1.0838043689727783',
   'distances2': '1.1260619163513184',
   'distances3': '1.2332398079294293',
   'distances4': '1.2647417783737183',
   'distances5': '1.3474191427230835',
   'distances6': '1.3757412433624268',
   'distances7': '1.3884904384613037',
   'documents0': 'vehicle, station wagon, pick-up truck, or van-type vehicle, but excludes recreational-type vehicles such as a "dune-buggy" or an "all-terrain" vehicle. The term "Seat Belt" means a factory-installed device that forms an occupant restraint and injury avoidance system. Article 5 - Loss of Use or Paralysis Benefit This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6015 Section B - Member Accidental Death and Dismemberment Insurance, Page 3',
   'documents1': 'Exposure Exposure to the elements will be presumed to be an injury if: a. such exposure is due to an accidental bodily injury; and b. within 365 days after the injury, the Member incurs a loss that is the result of the exposure; and c. this Group Policy would have covered the injury resulting from the accident. Article 4 - Seat Belt/Airbag Benefit If the Member loses his or her life as a result of an accidental injury sustained while driving or riding in an Automobile, an additional benefit of',
   'documents2': '$10,000 will be paid to the beneficiary named for Member Life Insurance, provided all Benefit Qualifications as described in Article 2 are met and: a. the Automobile is equipped with factory-installed Seat Belts; and b. the Seat Belt was in actual use by the Member and properly fastened at the time of the accident; and c. the position of the Seat Belt is certified in the official report of the accident or by the investigating officer. This additional benefit payment will also apply if the Member',
   'documents3': 'was driving an Automobile equipped with a properly functioning driver-side air bag or riding as a passenger in an Automobile equipped with a properly functioning passenger-side air bag, although the Member\'s Seat Belt may not have been fastened at the time of the accident. The properly functioning and/or deployment of the air bag must be certified in the official report of the accident or by the investigating officer. For the purpose of this benefit, "Automobile" means a four-wheel passenger',
   'documents4': 'Section A - Member Life Insurance Schedule of Insurance Article 1 Death Benefits Payable Article 2 Beneficiary Article 3 Facility of Payment Article 4 Settlement of Proceeds Article 5 Member Life Insurance - Coverage During Disability Article 6 Accelerated Benefits Article 7 Section B - Member Accidental Death and Dismemberment Insurance Schedule of Insurance Article 1 Benefit Qualification Article 2 Benefits Payable Article 3 Seat Belt Benefit Article 4 Loss of Use or Paralysis Benefit Article',
   'documents5': "death will be reduced by any Accelerated Benefit payment. e. Premium Waiver Period A premium waiver period will be established on the date The Principal pays an Accelerated Benefit to a Member. This period will end on the earlier of the Member's death or the date two years after the date of the Accelerated Benefit. During a premium waiver period: (1) there will be no Member Life and Member Accidental Death and Dismemberment Insurance and Dependent Life Insurance premium charge for the Member;",
   'documents6': 'Accidental Death and Dismemberment Insurance A person will be eligible for Member Accidental Death and Dismemberment Insurance on the latest of: a. the date the person is eligible for Member Life Insurance; or b. the date the person enters a class for which Member Accidental Death and Dismemberment Insurance is provided under this Group Policy; or c. the date Member Accidental Death and Dismemberment Insurance is added to this Group Policy. Article 3 - Dependent Life Insurance A person will be',
   'documents7': 'Article 2 - Benefit Qualification To qualify for benefit payment, all of the following must occur: a. the Member must be injured while insured for Member Accidental Death and Dismemberment Insurance under this Group Policy; and b. the injury must be through external, violent, and accidental means; and c. the injury must be the direct and sole cause of a loss listed in this Section B, Article 3; and d. the loss must occur within 365 days of the injury; and e. the limitations listed in this',
   'ids0': '201',
   'ids1': '198',
   'ids2': '199',
   'ids3': '200',
   'ids4': '14',
   'ids5': '187',
   'ids6': '78',
   'ids7': '191',
   'included0': 'd',
   'included1': 'i',
   'included2': 's',
   'included3': 't',
   'included4': 'a',
   'included5': 'n',
   'included6': 'c',
   'included7': 'e',
   'metadatas0': "{'Chunk_No.': 3, 'Page_No.': 'Page 55'}",
   'metadatas1': "{'Chunk_No.': 3, 'Page_No.': 'Page 55'}",
   'metadatas2': "{'Chunk_No.': 3, 'Page_No.': 'Page 55'}",
   'metadatas3': "{'Chunk_No.': 3, 'Page_No.': 'Page 55'}",
   'metadatas4': "{'Chunk_No.': 2, 'Page_No.': 'Page 8'}",
   'metadatas5': "{'Chunk_No.': 2, 'Page_No.': 'Page 52'}",
   'metadatas6': "{'Chunk_No.': 2, 'Page_No.': 'Page 26'}",
   'metadatas7': "{'Chunk_No.': 3, 'Page_No.': 'Page 53'}"}],
 'included': [<IncludeEnum.embeddings: 'embeddings'>,
  <IncludeEnum.documents: 'documents'>,
  <IncludeEnum.metadatas: 'metadatas'>]}

### Semantic Search with Cache

In [104]:
# Read the user query
query = input()

 what is the life insurance coverage for disability

In [106]:
# Searh the Cache collection first
# Query the collection against the user query and return the top 20 results
cache_results = cache_collection.query(
    query_texts=query,
    n_results=1
)

In [108]:
# get result from cache collection
cache_results

{'ids': [['what is the life insurance coverage for disability']],
 'embeddings': None,
 'documents': [['what is the life insurance coverage for disability']],
 'uris': None,
 'data': None,
 'metadatas': [[{'distances0': '0.7124123573303223',
    'distances1': '0.8027515411376953',
    'distances2': '0.8602005839347839',
    'distances3': '0.8729649186134338',
    'distances4': '0.8979799747467041',
    'distances5': '0.9084634184837341',
    'distances6': '0.9102334976196289',
    'distances7': '0.9125920534133911',
    'documents0': 'Member Life Insurance or Coverage During Disability terminates under this Group Policy. This policy has been updated effective January 1, 2014 PART III - INDIVIDUAL REQUIREMENTS AND RIGHTS GC 6011 Section F - Individual Purchase Rights, Page 1',
    'documents1': "Payment of benefits will be subject to the Beneficiary and Facility of Payment provisions of this PART IV, Section A. Article 6 - Member Life Insurance - Coverage During Disability A Member may be eligible to continue his or her Member Life and Member Accidental Death and Dismemberment Insurance and Dependent Life Insurance coverage during the Member's ADL Disability or Total Disability. a. Coverage Qualification To be qualified for Coverage During Disability, a Member must: (1) become ADL",
    'documents2': 'any Accelerated Benefit payment as described in PART IV, Section A, Article 7. Article 2 - Dependent Life Insurance a. Individual Policy If a Dependent qualifies and makes timely application, he or she may purchase an individual policy of life insurance under these terms: (1) The Dependent will not be required to submit Proof of Good Health. (2) The policy will be for life insurance only. No disability or other benefits will be included. (3) The policy will be on one of the forms, other than',
    'documents3': "Dependent's Life Insurance terminates because the Member's Coverage During Disability as described in PART IV, Section A, ceases because Total Disability ends and the Member does not return to Active Work within 31 days ; or (6) the Dependent's Life Insurance terminates because the Member's Accelerated Benefits Premium Waiver Period as described in PART IV, Section A, ceases and the Member does not qualify for Coverage During Disability. c. Application/Effective Date Notice of the individual",
    'documents4': 'disability that: (1) results from willful self-injury or self-destruction, while sane or insane; or (2) results from war or act of war; or (3) results from voluntary participation in an assault, felony, criminal activity, insurrection, or riot. Article 7 - Accelerated Benefits a. Accelerated Benefits Qualification To be qualified for an Accelerated Benefit payment, a Member must: (1) be Terminally Ill and insured for a Member Life Insurance benefit of at least $10,000; and (2) send a request for',
    'documents5': 'be the Coverage During Disability benefit in force on the date Total Disability ceases, less any individual policy amount purchased earlier under this Article 1, and less any Accelerated Benefit payment as described in PART IV, Section A, Article 7. (4) If termination is as described in b. (4) above, the maximum amount will be the Member Life Insurance benefit in force on the date the Member ceases Active Work, less any individual policy amount purchased earlier under this Article 1, and less',
    'documents6': 'Total Disability began. Failure to give Written proof within the time specified will not invalidate or reduce any claim if Written proof is given as soon as reasonably possible. Further, if a death benefit is paid under this section of the Group Policy, it will be in place of all other Member Life Insurance benefits provided under this Group Policy. f. Termination (Premium Waiver) This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance,',
    'documents7': 'terms of the Prior Policy, to have their premiums waived due to ADL Disability or Total Disability. NOTE: When insurance under this Group Policy replaces coverage under a Prior Policy and the Active Work requirement is waived, any benefits payable will be the lesser of the Scheduled Benefit of this Group Policy or the amount that would have been paid by the Prior Policy had it remained in force. b. Effective Date for Initial Insurance When Proof of Good Health is Required This policy has been',
    'ids0': '143',
    'ids1': '171',
    'ids2': '147',
    'ids3': '151',
    'ids4': '183',
    'ids5': '146',
    'ids6': '180',
    'ids7': '85',
    'included0': 'd',
    'included1': 'i',
    'included2': 's',
    'included3': 't',
    'included4': 'a',
    'included5': 'n',
    'included6': 'c',
    'included7': 'e',
    'metadatas0': "{'Chunk_No.': 4, 'Page_No.': 'Page 42'}",
    'metadatas1': "{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",
    'metadatas2': "{'Chunk_No.': 4, 'Page_No.': 'Page 43'}",
    'metadatas3': "{'Chunk_No.': 4, 'Page_No.': 'Page 44'}",
    'metadatas4': "{'Chunk_No.': 3, 'Page_No.': 'Page 51'}",
    'metadatas5': "{'Chunk_No.': 4, 'Page_No.': 'Page 43'}",
    'metadatas6': "{'Chunk_No.': 5, 'Page_No.': 'Page 50'}",
    'metadatas7': "{'Chunk_No.': 4, 'Page_No.': 'Page 28'}"}]],
 'distances': [[0.0]],
 'included': [<IncludeEnum.distances: 'distances'>,
  <IncludeEnum.documents: 'documents'>,
  <IncludeEnum.metadatas: 'metadatas'>]}

In [110]:
# get result from main collection
results = collection.query(
query_texts=query,
n_results=10
)
print("Result size is : " + str(len(results.items())))
results.items()

Result size is : 8

dict_items([('ids', [['143', '171', '147', '151', '183', '146', '180', '85', '179', '142']]), ('embeddings', None), ('documents', [['Member Life Insurance or Coverage During Disability terminates under this Group Policy. This policy has been updated effective January 1, 2014 PART III - INDIVIDUAL REQUIREMENTS AND RIGHTS GC 6011 Section F - Individual Purchase Rights, Page 1', "Payment of benefits will be subject to the Beneficiary and Facility of Payment provisions of this PART IV, Section A. Article 6 - Member Life Insurance - Coverage During Disability A Member may be eligible to continue his or her Member Life and Member Accidental Death and Dismemberment Insurance and Dependent Life Insurance coverage during the Member's ADL Disability or Total Disability. a. Coverage Qualification To be qualified for Coverage During Disability, a Member must: (1) become ADL", 'any Accelerated Benefit payment as described in PART IV, Section A, Article 7. Article 2 - Dependent Life Insurance a. Individual Policy If a Dependent qualifies and makes timely application, he or she may purchase an individual policy of life insurance under these terms: (1) The Dependent will not be required to submit Proof of Good Health. (2) The policy will be for life insurance only. No disability or other benefits will be included. (3) The policy will be on one of the forms, other than', "Dependent's Life Insurance terminates because the Member's Coverage During Disability as described in PART IV, Section A, ceases because Total Disability ends and the Member does not return to Active Work within 31 days ; or (6) the Dependent's Life Insurance terminates because the Member's Accelerated Benefits Premium Waiver Period as described in PART IV, Section A, ceases and the Member does not qualify for Coverage During Disability. c. Application/Effective Date Notice of the individual", 'disability that: (1) results from willful self-injury or self-destruction, while sane or insane; or (2) results from war or act of war; or (3) results from voluntary participation in an assault, felony, criminal activity, insurrection, or riot. Article 7 - Accelerated Benefits a. Accelerated Benefits Qualification To be qualified for an Accelerated Benefit payment, a Member must: (1) be Terminally Ill and insured for a Member Life Insurance benefit of at least $10,000; and (2) send a request for', 'be the Coverage During Disability benefit in force on the date Total Disability ceases, less any individual policy amount purchased earlier under this Article 1, and less any Accelerated Benefit payment as described in PART IV, Section A, Article 7. (4) If termination is as described in b. (4) above, the maximum amount will be the Member Life Insurance benefit in force on the date the Member ceases Active Work, less any individual policy amount purchased earlier under this Article 1, and less', 'Total Disability began. Failure to give Written proof within the time specified will not invalidate or reduce any claim if Written proof is given as soon as reasonably possible. Further, if a death benefit is paid under this section of the Group Policy, it will be in place of all other Member Life Insurance benefits provided under this Group Policy. f. Termination (Premium Waiver) This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance,', 'terms of the Prior Policy, to have their premiums waived due to ADL Disability or Total Disability. NOTE: When insurance under this Group Policy replaces coverage under a Prior Policy and the Active Work requirement is waived, any benefits payable will be the lesser of the Scheduled Benefit of this Group Policy or the amount that would have been paid by the Prior Policy had it remained in force. b. Effective Date for Initial Insurance When Proof of Good Health is Required This policy has been', "Disability is in force, The Principal will pay the Member's beneficiary the Member Life Insurance benefit amount that would have been paid had the Member remained insured under the Schedule of Insurance in force on the date Total Disability began. Such benefit shall be subject to any reduction provided under the Schedule of Insurance. However, NO BENEFIT WILL BE PAID if Written proof of ADL Disability or Total Disability is not sent to The Principal within one year of the date ADL Disability or", 'Premium Waiver Period as described in PART IV, Section A, ceases and he or she does not qualify for Coverage During Disability . c. Application/Effective Date Notice of the individual purchase right must be given to the Member by the Policyholder before insurance under this Group Policy terminates, or as soon as reasonably possible thereafter. A Member must apply for individual purchase and the first premium for the individual policy must be paid to The Principal within 31 days after the date']]), ('uris', None), ('data', None), ('metadatas', [[{'Chunk_No.': 4, 'Page_No.': 'Page 42'}, {'Chunk_No.': 4, 'Page_No.': 'Page 49'}, {'Chunk_No.': 4, 'Page_No.': 'Page 43'}, {'Chunk_No.': 4, 'Page_No.': 'Page 44'}, {'Chunk_No.': 3, 'Page_No.': 'Page 51'}, {'Chunk_No.': 4, 'Page_No.': 'Page 43'}, {'Chunk_No.': 5, 'Page_No.': 'Page 50'}, {'Chunk_No.': 4, 'Page_No.': 'Page 28'}, {'Chunk_No.': 5, 'Page_No.': 'Page 50'}, {'Chunk_No.': 4, 'Page_No.': 'Page 42'}]]), ('distances', [[0.7124123573303223, 0.8027515411376953, 0.8602005839347839, 0.8729649186134338, 0.8979799747467041, 0.9084634184837341, 0.9102334976196289, 0.9125920534133911, 0.9250823259353638, 0.9328154921531677]]), ('included', [<IncludeEnum.distances: 'distances'>, <IncludeEnum.documents: 'documents'>, <IncludeEnum.metadatas: 'metadatas'>])])

In [112]:
# Implementing Cache in Semantic Search

# Set a threshold for cache search
threshold = 0.2

ids = []
documents = []
distances = []
metadatas = []
results_df = pd.DataFrame()


# If the distance is greater than the threshold, then return the results from the main collection.

if cache_results['distances'][0] == [] or cache_results['distances'][0][0] > threshold:
      # Query the collection against the user query and return the top 10 results
      results = collection.query(
      query_texts=query,
      n_results=10
      )

      # Store the query in cache_collection as document w.r.t to ChromaDB so that it can be embedded and searched against later
      # Store retrieved text, ids, distances and metadatas in cache_collection as metadatas, so that they can be fetched easily if a query indeed matches to a query in cache
      Keys = []
      Values = []

      size = len(results.items())

      for key, val in results.items():
        if val is None:
          continue
        for i in range(size):
          Keys.append(str(key)+str(i))
          Values.append(str(val[0][i]))


      cache_collection.add(
          documents= [query],
          ids = [query],  # Or if you want to assign integers as IDs 0,1,2,.., then you can use "len(cache_results['documents'])" as will return the no. of queries currently in the cache and assign the next digit to the new query."
          metadatas = dict(zip(Keys, Values))
      )

      print("Not found in cache. Found in main collection.")

      result_dict = {'Metadatas': results['metadatas'][0], 'Documents': results['documents'][0], 'Distances': results['distances'][0], "IDs":results["ids"][0]}
      results_df = pd.DataFrame.from_dict(result_dict)
      results_df


# If the distance is, however, less than the threshold, you can return the results from cache

elif cache_results['distances'][0][0] <= threshold:
      cache_result_dict = cache_results['metadatas'][0][0]

      # Loop through each inner list and then through the dictionary
      for key, value in cache_result_dict.items():
          if 'ids' in key:
              ids.append(value)
          elif 'documents' in key:
              documents.append(value)
          elif 'distances' in key:
              distances.append(value)
          elif 'metadatas' in key:
              metadatas.append(value)

      print("Found in cache!")

      # Create a DataFrame
      results_df = pd.DataFrame({
        'IDs': ids,
        'Documents': documents,
        'Distances': distances,
        'Metadatas': metadatas
      })

Found in cache!

In [114]:
# print the results
results_df

,IDs,Documents,Distances,Metadatas
0,143,Member Life Insurance or Coverage During Disab...,0.7124123573303223,"{'Chunk_No.': 4, 'Page_No.': 'Page 42'}"
1,171,Payment of benefits will be subject to the Ben...,0.8027515411376953,"{'Chunk_No.': 4, 'Page_No.': 'Page 49'}"
2,147,any Accelerated Benefit payment as described i...,0.8602005839347839,"{'Chunk_No.': 4, 'Page_No.': 'Page 43'}"
3,151,Dependent's Life Insurance terminates because ...,0.8729649186134338,"{'Chunk_No.': 4, 'Page_No.': 'Page 44'}"
4,183,disability that: (1) results from willful self...,0.8979799747467041,"{'Chunk_No.': 3, 'Page_No.': 'Page 51'}"
5,146,be the Coverage During Disability benefit in f...,0.9084634184837341,"{'Chunk_No.': 4, 'Page_No.': 'Page 43'}"
6,180,Total Disability began. Failure to give Writte...,0.9102334976196289,"{'Chunk_No.': 5, 'Page_No.': 'Page 50'}"
7,85,"terms of the Prior Policy, to have their premi...",0.9125920534133911,"{'Chunk_No.': 4, 'Page_No.': 'Page 28'}"

### Re-Ranking with a Cross Encoder

In [118]:
# Import the CrossEncoder library from sentence_transformers
from sentence_transformers import CrossEncoder

In [120]:
# Initialise the cross encoder model
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

In [122]:
# Input (query, response) pairs for each of the top 20 responses received from the semantic search to the cross encoder
# Generate the cross_encoder scores for these pairs

cross_inputs = [[query, response] for response in results_df['Documents']]
cross_rerank_scores = cross_encoder.predict(cross_inputs)

In [124]:
# pritn the cross rerank scores
cross_rerank_scores

array([ 3.0535288 ,  4.810114  ,  0.5387689 ,  2.9317641 , -0.90366566,
        1.4724658 ,  0.26232514, -1.3536794 ], dtype=float32)

In [126]:
results_df['Reranked_scores'] = cross_rerank_scores

In [128]:
results_df

,IDs,Documents,Distances,Metadatas,Reranked_scores
0,143,Member Life Insurance or Coverage During Disab...,0.7124123573303223,"{'Chunk_No.': 4, 'Page_No.': 'Page 42'}",3.053529
1,171,Payment of benefits will be subject to the Ben...,0.8027515411376953,"{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",4.810114
2,147,any Accelerated Benefit payment as described i...,0.8602005839347839,"{'Chunk_No.': 4, 'Page_No.': 'Page 43'}",0.538769
3,151,Dependent's Life Insurance terminates because ...,0.8729649186134338,"{'Chunk_No.': 4, 'Page_No.': 'Page 44'}",2.931764
4,183,disability that: (1) results from willful self...,0.8979799747467041,"{'Chunk_No.': 3, 'Page_No.': 'Page 51'}",-0.903666
5,146,be the Coverage During Disability benefit in f...,0.9084634184837341,"{'Chunk_No.': 4, 'Page_No.': 'Page 43'}",1.472466
6,180,Total Disability began. Failure to give Writte...,0.9102334976196289,"{'Chunk_No.': 5, 'Page_No.': 'Page 50'}",0.262325
7,85,"terms of the Prior Policy, to have their premi...",0.9125920534133911,"{'Chunk_No.': 4, 'Page_No.': 'Page 28'}",-1.353679

In [130]:
# Return the top 3 results from semantic search

top_3_semantic = results_df.sort_values(by='Distances')
top_3_semantic[:3]

,IDs,Documents,Distances,Metadatas,Reranked_scores
0,143,Member Life Insurance or Coverage During Disab...,0.7124123573303223,"{'Chunk_No.': 4, 'Page_No.': 'Page 42'}",3.053529
1,171,Payment of benefits will be subject to the Ben...,0.8027515411376953,"{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",4.810114
2,147,any Accelerated Benefit payment as described i...,0.8602005839347839,"{'Chunk_No.': 4, 'Page_No.': 'Page 43'}",0.538769

In [132]:
# Return the top 3 results after reranking

top_3_rerank = results_df.sort_values(by='Reranked_scores', ascending=False)
top_3_rerank[:3]

,IDs,Documents,Distances,Metadatas,Reranked_scores
1,171,Payment of benefits will be subject to the Ben...,0.8027515411376953,"{'Chunk_No.': 4, 'Page_No.': 'Page 49'}",4.810114
0,143,Member Life Insurance or Coverage During Disab...,0.7124123573303223,"{'Chunk_No.': 4, 'Page_No.': 'Page 42'}",3.053529
3,151,Dependent's Life Insurance terminates because ...,0.8729649186134338,"{'Chunk_No.': 4, 'Page_No.': 'Page 44'}",2.931764

In [134]:
top_3_RAG = top_3_rerank[["Documents", "Metadatas"]][:3]
top_3_RAG

,Documents,Metadatas
1,Payment of benefits will be subject to the Ben...,"{'Chunk_No.': 4, 'Page_No.': 'Page 49'}"
0,Member Life Insurance or Coverage During Disab...,"{'Chunk_No.': 4, 'Page_No.': 'Page 42'}"
3,Dependent's Life Insurance terminates because ...,"{'Chunk_No.': 4, 'Page_No.': 'Page 44'}"

### Retrieval Augmented Generation

In [138]:
# Set the API key
with open("OpenAI_API_Key.txt", "r") as f:
  openai.api_key = ' '.join(f.readlines())

In [146]:
# Define the function to generate the response. Provide a comprehensive prompt that passes the user query and the top 3 results to the model

def generate_response(query, results_df):
    """
    Generate a response using GPT-3.5's ChatCompletion based on the user query and retrieved information.
    """
    messages = [
                {"role": "system", "content":  "You are a helpful assistant in the insurance domain who can effectively answer user queries about insurance policies and documents."},
                {"role": "user", "content": f"""You are a helpful assistant in the insurance domain who can effectively answer user queries about insurance policies and documents.
                                                You have a question asked by the user in '{query}' and you have some search results from a corpus of insurance documents in the dataframe '{top_3_RAG}'. These search results are essentially one page of an insurance document that may be relevant to the user query.

                                                The column 'documents' inside this dataframe contains the actual text from the policy document and the column 'metadata' contains the policy name and source page. The text inside the document may also contain tables in the format of a list of lists where each of the nested lists indicates a row.

                                                Use the documents in '{top_3_RAG}' to answer the query '{query}'. Frame an informative answer and also, use the dataframe to return the relevant policy names and page numbers as citations.

                                                Follow the guidelines below when performing the task.
                                                1. Try to provide relevant/accurate numbers if available.
                                                2. You don’t have to necessarily use all the information in the dataframe. Only choose information that is relevant.
                                                3. If the document text has tables with relevant information, please reformat the table and return the final information in a tabular in format.
                                                3. Use the Metadatas columns in the dataframe to retrieve and cite the policy name(s) and page numbers(s) as citation.
                                                4. If you can't provide the complete answer, please also provide any information that will help the user to search specific sections in the relevant cited documents.
                                                5. You are a customer facing assistant, so do not provide any information on internal workings, just answer the query directly.

                                                The generated response should answer the query directly addressing the user and avoiding additional information. If you think that the query is not relevant to the document, reply that the query is irrelevant. Provide the final response as a well-formatted and easily readable text along with the citation. Provide your complete response first with all information, and then provide the citations.
                                                """},
              ]

    response = openai.chat.completions.create(
        model="gpt-4o-mini",
        messages=messages
    )

    return response.choices[0].message.content.split('\n')

In [148]:
# Generate the response
response = generate_response(query, top_3_RAG)

In [149]:
# Print the response
print("\n".join(response))

In relation to life insurance coverage for disability, it is important to note that member life insurance generally covers death benefits; however, there might be specific provisions regarding coverage during periods of disability.

The policy may provide that benefits will be subject to certain conditions when a member becomes disabled. Typically, this means that while the individual is disabled, they may be eligible for a different structure of benefits, which could include a continuation of their life insurance coverage or adjustments to the premiums.

Additionally, dependent life insurance usually terminates if the insured member becomes disabled, which could have implications for the overall coverage.

For more detailed information on these aspects, I would recommend reviewing the specific sections in your insurance documents that discuss life insurance coverage during disability. Below is a summarized overview of where to find relevant information:

| Policy Name                                             | Page Number |
|--------------------------------------------------------|-------------|
| Member Life Insurance or Coverage During Disability    | Page 42    |
| Payment of Benefits Will Be Subject to the Beneficiary Provisions | Page 49    |
| Dependent's Life Insurance          | Page 44       |

These references should lead you to the pertinent information regarding your inquiry about life insurance coverage during disability.

### Queries

In [154]:
def search(query):

  # Set a threshold for cache search
  threshold = 0.2

  ids = []
  documents = []
  distances = []
  metadatas = []
  results_df = pd.DataFrame()

  # try to find from cache
  cache_results = cache_collection.query(
      query_texts=query,
      n_results=1
  )

  # If the distance is greater than the threshold, then return the results from the main collection.
  if cache_results['distances'][0] == [] or cache_results['distances'][0][0] > threshold:
        # Query the collection against the user query and return the top 10 results
        results = collection.query(
        query_texts=query,
        n_results=10
        )

        # Store the query in cache_collection as document w.r.t to ChromaDB so that it can be embedded and searched against later
        # Store retrieved text, ids, distances and metadatas in cache_collection as metadatas, so that they can be fetched easily if a query indeed matches to a query in cache
        Keys = []
        Values = []

        size = len(results.items())

        for key, val in results.items():
          if val is None:
            continue
          for i in range(size):
            Keys.append(str(key)+str(i))
            Values.append(str(val[0][i]))


        cache_collection.add(
            documents= [query],
            ids = [query],  # Or if you want to assign integers as IDs 0,1,2,.., then you can use "len(cache_results['documents'])" as will return the no. of queries currently in the cache and assign the next digit to the new query."
            metadatas = dict(zip(Keys, Values))
        )

        #print("Not found in cache. Found in main collection.")

        result_dict = {'Metadatas': results['metadatas'][0], 'Documents': results['documents'][0], 'Distances': results['distances'][0], "IDs":results["ids"][0]}
        results_df = pd.DataFrame.from_dict(result_dict)
        return results_df


  # If the distance is, however, less than the threshold, you can return the results from cache

  elif cache_results['distances'][0][0] <= threshold:
        cache_result_dict = cache_results['metadatas'][0][0]

        # Loop through each inner list and then through the dictionary
        for key, value in cache_result_dict.items():
            if 'ids' in key:
                ids.append(value)
            elif 'documents' in key:
                documents.append(value)
            elif 'distances' in key:
                distances.append(value)
            elif 'metadatas' in key:
                metadatas.append(value)

        #print("Found in cache!")

        # Create a DataFrame
        return pd.DataFrame({
          'IDs': ids,
          'Documents': documents,
          'Distances': distances,
          'Metadatas': metadatas
        })

In [156]:
def apply_cross_encoder(query, df):
  cross_inputs = [[query, response] for response in df['Documents']]
  cross_rerank_scores = cross_encoder.predict(cross_inputs)
  df['Reranked_scores'] = cross_rerank_scores
  return df

In [158]:
def get_topn(n, df):
  top_3_rerank = df.sort_values(by='Reranked_scores', ascending=False)
  return top_3_rerank[["Documents", "Metadatas"]][:n]

In [160]:
query = 'what is the life insurance coverage for disability'
df = search(query)
df = apply_cross_encoder(query, df)
df = get_topn(3, df)
response = generate_response(query, df)
print("\n".join(response))

Life insurance coverage for disability typically refers to the benefits that may be paid out if a policyholder becomes disabled. Based on the available documents, here are the relevant details:

1. **Member Life Insurance During Disability**: The policy provides information on how member life insurance coverage operates in the event of a disability. This can articulate the terms under which life insurance benefits are payable during periods of disability.

2. **Dependent's Life Insurance**: It's also noted that a dependent's life insurance can be affected if a member becomes disabled, which could lead to termination of coverage.

Unfortunately, the specific coverage amounts or percentages aren't detailed in the provided excerpts. For precise benefit amounts, you may want to refer to the relevant sections in the documents above.

Here is a summary of the references provided:

| Policy Name                                             | Page Number |
|--------------------------------------------------------|-------------|
| Member Life Insurance or Coverage During Disability     | Page 42    |
| Dependent's Life Insurance                              | Page 44    |
| Payment of benefits will be subject to the Beneficiary terms | Page 49    |

For further details, checking the sections mentioned in the policies would provide comprehensive information specific to your situation.

**Citations**:
- Member Life Insurance or Coverage During Disability - Page 42
- Dependent's Life Insurance - Page 44
- Payment of benefits will be subject to the Beneficiary terms - Page 49

In [161]:
query = 'what is the Proof of ADL Disability or Total Disability'
df = search(query)
df = apply_cross_encoder(query, df)
df = get_topn(3, df)
response = generate_response(query, df)
print("\n".join(response))

Proof of Activities of Daily Living (ADL) Disability or Total Disability typically involves providing specific documentation that demonstrates an individual's inability to engage in essential daily activities due to a medical condition or injury. Such proof often includes evaluations from qualified healthcare professionals, detailed medical records, and potentially assessments of the individual's ability to perform these activities safely.

The criteria for ADL disability generally focus on the individual's ability to perform the following tasks:

1. **Bathing**: Ability to wash oneself.
2. **Dressing**: Ability to put on and take off clothing.
3. **Eating**: Ability to feed oneself.
4. **Toileting**: Ability to get to and from the toilet and manage personal hygiene.
5. **Transferring**: Ability to move from one position to another (such as from bed to a chair).
6. **Continence**: Ability to control bowel and bladder function.

It is crucial to consult the specific insurance policy for the definitions and requirements applied to ADL disability. Review your policy documents for details regarding what is required for proof of disability and the claims process.

For more specific information concerning your policy, you may refer to the following document excerpts regarding Member Life Insurance and Disability Benefits:

| Policy Name                                             | Page Number |
|--------------------------------------------------------|-------------|
| Member Life Insurance or Coverage During Disability     | Page 42    |
| Payment of benefits will be subject to the Benefit terms| Page 49    |
| Dependent's Life Insurance                               | Page 44    |

These sections outline important stipulations related to disability claims. For the most accurate and detailed information, reviewing these specific pages is recommended.

**Citations:**
- Member Life Insurance or Coverage During Disability (Page 42)
- Payment of benefits will be subject to the Benefit terms (Page 49)
- Dependent's Life Insurance (Page 44)

In [164]:
query = 'what is condition of deatht while not wearing Seat Belt'
df = search(query)
df = apply_cross_encoder(query, df)
df = get_topn(3, df)
response = generate_response(query, df)
print("\n".join(response))

The condition of death while not wearing a seat belt can often affect the benefits payable under an auto insurance policy, particularly in relation to life insurance and accidental deaths. Generally, if a policyholder dies in a vehicle accident while not wearing a seat belt, insurers may scrutinize the circumstances and determine whether the omission was a contributing factor to the fatality. This may lead to a reduction in the benefits or even a denial of the claim altogether.

To understand the specific implications under your insurance policy, please refer to the following sections from relevant documents:

| Policy Name                                              | Page Number |
|---------------------------------------------------------|-------------|
| Member Life Insurance or Coverage During Disability     | Page 42     |
| Payment of benefits will be subject to the Benefits clause | Page 49     |
| Dependent's Life Insurance                               | Page 44     |

These documents will provide you with detailed terms concerning the payment of benefits and any exclusions that may apply in the case of non-compliance with safety regulations, such as wearing a seat belt. Please review these sections for precise conditions affecting claims related to not wearing a seat belt in the event of a fatal accident.

**Citations:**
- Member Life Insurance or Coverage During Disability, Page 42
- Payment of benefits will be subject to the Benefits clause, Page 49
- Dependent's Life Insurance, Page 44