In [16]:
#Import the required Libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Cleaning

### Data Reading & Data Types

In [17]:
#Read the data in pandas
inp0= pd.read_csv("Attribute+DataSet.csv")
inp1= pd.read_csv("Dress+Sales.csv")

You have “Attribute DataSet” which contains a column named “Price”. Choose the correct statement from the following about its data type and variable type.
- Integer type and numerical variable
- Object type and categorical ordinal variable
- Object type and categorical nominal variable
- Float type and categorical variable.

There is another column in “Attribute DataSet” named as “Recommendation”, choose the correct statement about its data type and variable type.
- Integer type and categorical
- Object type and categorical
- Integer type and continuous numerical
- Object type only.

Which of the following column do you think are of no use in “Attribute DataSet”.
- Dress_ID
- Price
- Size and material
- NeckLine
- None of the above

In [18]:
# Print the information about the attributes of inp0 and inp1.
inp0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Dress_ID        479 non-null    int64
 1   Style           479 non-null    object
 2   Price           477 non-null    object
 3   Rating          479 non-null    float64
 4   Size            479 non-null    object
 5   Season          477 non-null    object
 6   NeckLine        476 non-null    object
 7   SleeveLength    477 non-null    object
 8   Material        360 non-null    object
 9   FabricType      223 non-null    object
 10  Decoration      255 non-null    object
 11  Pattern Type    377 non-null    object
 12  Recommendation  479 non-null    int64
dtypes: float64(1), int64(2), object(10)
memory usage: 48.8+ KB

In [19]:
inp1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Dress_ID    479 non-null    float64
 1   29-08-2013  479 non-null    int64
 2   31-08-2013  479 non-null    int64
 3   09-02-2013  479 non-null    int64
 4   09-04-2013  479 non-null    int64
 5   09-06-2013  479 non-null    int64
 6   09-08-2013  479 non-null    int64
 7   09-10-2013  479 non-null    int64
 8   09-12-2013  479 non-null    object
 9   14-09-2013  479 non-null    object
 10  16-09-2013  479 non-null    object
 11  18-09-2013  479 non-null    object
 12  20-09-2013  479 non-null    object
 13  22-09-2013  479 non-null    object
 14  24-09-2013  479 non-null    int64
 15  26-09-2013  257 non-null    float64
 16  28-09-2013  479 non-null    int64
 17  30-09-2013  222 non-null    float64
 18  10-02-2013  220 non-null    float64
 19  10-04-2013  221 non-null    float64
 20  10-06-2013  479 non-null    int64
 21  10-08-2013  224 non-null    float64
 22  10-10-2013  224 non-null    float64
 23  10-12-2013  479 non-null    int64
dtypes: float64(7), int64(11), object(6)
memory usage: 89.9+ KB

In [20]:
inp0.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,chiffonfabric,chiffon,bow,dot,0

In [21]:
inp1.head()

,Dress_ID,29-08-2013,31-08-2013,09-02-2013,09-04-2013,09-06-2013,09-08-2013,09-10-2013,09-12-2013,14-09-2013,...,24-09-2013,26-09-2013,28-09-2013,30-09-2013,10-02-2013,10-04-2013,10-06-2013,10-08-2013,10-10-2013,10-12-2013
0,1.006033e+09,2114,2274,2491,2660,2727,2887,2930,3119,3204,...,3554,3624.0,3706,3746.0,3795.0,3832.0,3897,3923.0,3985.0,4048
1,1.212192e+09,151,275,570,750,813,1066,1164,1558,1756,...,2710,2942.0,3258,3354.0,3475.0,3654.0,3911,4024.0,4125.0,4277
2,1.190381e+09,6,7,7,7,8,8,9,10,10,...,11,11.0,11,11.0,11.0,11.0,11,11.0,11.0,11
3,9.660060e+08,1005,1128,1326,1455,1507,1621,1637,1723,1746,...,1878,1892.0,1914,1924.0,1929.0,1941.0,1952,1955.0,1959.0,1963
4,8.763395e+08,996,1175,1304,1396,1432,1559,1570,1638,1655,...,2032,2156.0,2252,2312.0,2387.0,2459.0,2544,2614.0,2693.0,2736

### Fixing the Rows and Columns

As you can see, there is a column in “Attribute Dataset” named as ‘Size’. This column contains the values in abbreviation format. Write a code in Python to convert the followings:

- M into  “Medium”
- L into  “Large”
- XL into “Extra large”
- free into “Free”
- S, s & small into “Small”.

Now once you are done with changes in the dataset, what is the value of the lowest percentage, the highest percentage and the percentage of Small size categories in the column named “Size”?

In [22]:
inp0['Size'].value_counts()

Size
M        171
free     165
L         93
S         34
XL        14
small      1
s          1
Name: count, dtype: int64

In [23]:
# Column fixing, correcting size abbreviation. count the percentage of each size category in "Size" column.

def updateSize(x):
    if x=="M":
        return "Medium"
    elif x=="L":
        return "Large"
    elif x=="XL":
        return "Extra large"
    elif x=="free":
        return "Free"
    else:
        return "Small"

inp0['Size'] = inp0['Size'].apply(lambda x: updateSize(x))

In [24]:
# Print the value counts of each category in "Size" column.
inp0['Size'].value_counts()

Size
Medium         171
Free           165
Large           93
Small           36
Extra large     14
Name: count, dtype: int64

In [25]:
inp0['Size'].value_counts(normalize=True)

Size
Medium         0.356994
Free           0.344468
Large          0.194154
Small          0.075157
Extra large    0.029228
Name: proportion, dtype: float64

### Impute/Remove Missing values

In [26]:
# Print the null count of each variables of inp0 and inp1.
inp0.isnull().sum()

Dress_ID            0
Style               0
Price               2
Rating              0
Size                0
Season              2
NeckLine            3
SleeveLength        2
Material          119
FabricType        256
Decoration        224
Pattern Type      102
Recommendation      0
dtype: int64

In [27]:
inp1.isnull().sum()

Dress_ID        0
29-08-2013      0
31-08-2013      0
09-02-2013      0
09-04-2013      0
09-06-2013      0
09-08-2013      0
09-10-2013      0
09-12-2013      0
14-09-2013      0
16-09-2013      0
18-09-2013      0
20-09-2013      0
22-09-2013      0
24-09-2013      0
26-09-2013    222
28-09-2013      0
30-09-2013    257
10-02-2013    259
10-04-2013    258
10-06-2013      0
10-08-2013    255
10-10-2013    255
10-12-2013      0
dtype: int64

You are given another dataset named “Dress Sales”. Now if you observe the datatypes of the columns using ‘inp1.info()’ command, you can identify that there are certain columns defined as object data type though they primarily consist of numeric data.

Now if you try and convert these object data type columns into numeric data type(float), you will come across an error message. Try to correct this error.

In [28]:
# Print the data types information of inp1 i.e. "Dress Sales" data.
inp1["09-12-2013"].value_counts()

09-12-2013
1       9
2       9
3       8
25      6
5       6
       ..
111     1
549     1
455     1
1886    1
268     1
Name: count, Length: 311, dtype: int64

In [29]:
# Try to convert the object type into float type of data. YOU GET ERROR MESSAGE.
inp1['09-12-2013'] = inp1['09-12-2013'].astype('float')

ValueError: could not convert string to float: 'Removed'

In [30]:
# Do the required changes in the "Dress Sales" data set to get null values on string values.
inp1["09-12-2013"] = inp1["09-12-2013"].apply(lambda x: np.NaN if (x == 'Removed' or x == 'removed') else x)

In [31]:
# Convert the object type columns in "Dress Sales" into float type of data type.
inp1['09-12-2013'] = inp1['09-12-2013'].astype('float')

In [32]:
inp1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Dress_ID    479 non-null    float64
 1   29-08-2013  479 non-null    int64
 2   31-08-2013  479 non-null    int64
 3   09-02-2013  479 non-null    int64
 4   09-04-2013  479 non-null    int64
 5   09-06-2013  479 non-null    int64
 6   09-08-2013  479 non-null    int64
 7   09-10-2013  479 non-null    int64
 8   09-12-2013  478 non-null    float64
 9   14-09-2013  479 non-null    object
 10  16-09-2013  479 non-null    object
 11  18-09-2013  479 non-null    object
 12  20-09-2013  479 non-null    object
 13  22-09-2013  479 non-null    object
 14  24-09-2013  479 non-null    int64
 15  26-09-2013  257 non-null    float64
 16  28-09-2013  479 non-null    int64
 17  30-09-2013  222 non-null    float64
 18  10-02-2013  220 non-null    float64
 19  10-04-2013  221 non-null    float64
 20  10-06-2013  479 non-null    int64
 21  10-08-2013  224 non-null    float64
 22  10-10-2013  224 non-null    float64
 23  10-12-2013  479 non-null    int64
dtypes: float64(8), int64(11), object(5)
memory usage: 89.9+ KB

In [33]:
inp1["14-09-2013"] = inp1["14-09-2013"].apply(lambda x: np.NaN if (x == 'Removed' or x == 'removed') else x)
inp1['14-09-2013'] = inp1['14-09-2013'].astype('float')

In [34]:
inp1["16-09-2013"] = inp1["16-09-2013"].apply(lambda x: np.NaN if (x == 'Removed' or x == 'removed') else x)
inp1['16-09-2013'] = inp1['16-09-2013'].astype('float')

In [35]:
inp1["18-09-2013"] = inp1["18-09-2013"].apply(lambda x: np.NaN if (x == 'Removed' or x == 'removed') else x)
inp1['18-09-2013'] = inp1['18-09-2013'].astype('float')

In [36]:
inp1["20-09-2013"] = inp1["20-09-2013"].apply(lambda x: np.NaN if (x == 'Removed' or x == 'removed') else x)
inp1['20-09-2013'] = inp1['20-09-2013'].astype('float')

In [37]:
inp1["22-09-2013"] = inp1["22-09-2013"].apply(lambda x: np.NaN if (x == 'Removed' or x == 'removed' or x == 'Orders') else x)
inp1['22-09-2013'] = inp1['22-09-2013'].astype('float')

In [38]:
inp1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Dress_ID    479 non-null    float64
 1   29-08-2013  479 non-null    int64
 2   31-08-2013  479 non-null    int64
 3   09-02-2013  479 non-null    int64
 4   09-04-2013  479 non-null    int64
 5   09-06-2013  479 non-null    int64
 6   09-08-2013  479 non-null    int64
 7   09-10-2013  479 non-null    int64
 8   09-12-2013  478 non-null    float64
 9   14-09-2013  478 non-null    float64
 10  16-09-2013  478 non-null    float64
 11  18-09-2013  478 non-null    float64
 12  20-09-2013  478 non-null    float64
 13  22-09-2013  478 non-null    float64
 14  24-09-2013  479 non-null    int64
 15  26-09-2013  257 non-null    float64
 16  28-09-2013  479 non-null    int64
 17  30-09-2013  222 non-null    float64
 18  10-02-2013  220 non-null    float64
 19  10-04-2013  221 non-null    float64
 20  10-06-2013  479 non-null    int64
 21  10-08-2013  224 non-null    float64
 22  10-10-2013  224 non-null    float64
 23  10-12-2013  479 non-null    int64
dtypes: float64(13), int64(11)
memory usage: 89.9 KB

When you see the null counts in “Dress Sales” dataset after performing all the operations that have been mentioned in jupyter notebook, you will find that there are some columns in “Dress Sales” data where there are more than 40% of missing values. Based on your understanding of dealing with missing values do the following steps.

In [39]:
# Print the null percetange of each column of inp1.
print(inp1.shape)

inp1.isnull().sum()

(479, 24)

Dress_ID        0
29-08-2013      0
31-08-2013      0
09-02-2013      0
09-04-2013      0
09-06-2013      0
09-08-2013      0
09-10-2013      0
09-12-2013      1
14-09-2013      1
16-09-2013      1
18-09-2013      1
20-09-2013      1
22-09-2013      1
24-09-2013      0
26-09-2013    222
28-09-2013      0
30-09-2013    257
10-02-2013    259
10-04-2013    258
10-06-2013      0
10-08-2013    255
10-10-2013    255
10-12-2013      0
dtype: int64

In [40]:
# Drop the columns in "Dress Sales" which have more than 40% of missing values.
inp1.drop(columns =['26-09-2013','30-09-2013','10-02-2013','10-04-2013','10-08-2013','10-10-2013'],inplace=True)

You should categorise the dates into seasons in “Dress Sales” data to simplify the analysis according to the following criteria:
- June, July and August: Summer.
- September, October and November: Autumn.
- December, January and February: WInter.
- March, April and May: Spring.

In [41]:
# Create the four seasons columns in inp1, according to the above criteria.
Summer = (inp1[['29-08-2013','31-08-2013','09-06-2013','09-08-2013', '10-06-2013']].sum()).sum()

Autumn = (inp1[['09-10-2013', '14-09-2013','16-09-2013', '18-09-2013', '20-09-2013', '22-09-2013', '24-09-2013',
       '28-09-2013']].sum()).sum()

Winter = (inp1[['09-02-2013','10-12-2013']].sum()).sum()

Spring = (inp1['09-04-2013'].sum()).sum()

In [42]:
# calculate the sum of sales in each seasons in inp1 i.e. "Dress Sales".
print(Summer)
print(Autumn)
print(Winter)
print(Spring)

691907
1363288.0
314990
143600

In [43]:
inp1['Spring'] = inp1.apply(lambda x: x['09-04-2013'], axis=1)

inp1['Summer'] = inp1.apply(lambda x: x['29-08-2013'] + x['31-08-2013']+ x['09-06-2013']+ x['09-08-2013']+ x['10-06-2013'], axis=1)

inp1['Winter'] = inp1.apply(lambda x: x['09-02-2013'] + x['09-12-2013']+ x['10-12-2013'], axis=1)

inp1['Autumn'] = inp1.apply(lambda x: x['09-10-2013'] + x['14-09-2013']+ x['16-09-2013']+ x['18-09-2013']+ x['20-09-2013']+ x['22-09-2013']+ x['24-09-2013']+ x['28-09-2013'], axis=1)

In [44]:
inp1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Dress_ID    479 non-null    float64
 1   29-08-2013  479 non-null    int64
 2   31-08-2013  479 non-null    int64
 3   09-02-2013  479 non-null    int64
 4   09-04-2013  479 non-null    int64
 5   09-06-2013  479 non-null    int64
 6   09-08-2013  479 non-null    int64
 7   09-10-2013  479 non-null    int64
 8   09-12-2013  478 non-null    float64
 9   14-09-2013  478 non-null    float64
 10  16-09-2013  478 non-null    float64
 11  18-09-2013  478 non-null    float64
 12  20-09-2013  478 non-null    float64
 13  22-09-2013  478 non-null    float64
 14  24-09-2013  479 non-null    int64
 15  28-09-2013  479 non-null    int64
 16  10-06-2013  479 non-null    int64
 17  10-12-2013  479 non-null    int64
 18  Spring      479 non-null    float64
 19  Summer      479 non-null    float64
 20  Winter      478 non-null    float64
 21  Autumn      477 non-null    float64
dtypes: float64(11), int64(11)
memory usage: 82.5 KB

Now let's merge inp1 with inp0 with left join manner, so that the information of inp0 should remain intact.

In [45]:
# Merge inp0 with inp1 into inp0. this is also called left merge.
inp0 = pd.merge(left=inp0,right=inp1, how='left', left_on='Dress_ID', right_on='Dress_ID')
inp0.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,...,20-09-2013,22-09-2013,24-09-2013,28-09-2013,10-06-2013,10-12-2013,Spring,Summer,Winter,Autumn
0,1006032852,Sexy,Low,4.6,Medium,Summer,o-neck,sleevless,NaN,chiffon,...,3386.0,3479.0,3554,3706,3897,4048,2660.0,13899.0,9658.0,26857.0
1,1212192089,Casual,Low,0.0,Large,Summer,o-neck,Petal,microfiber,NaN,...,2106.0,2454.0,2710,3258,3911,4277,750.0,6216.0,6405.0,17311.0
2,1190380701,vintage,High,0.0,Large,Automn,o-neck,full,polyster,NaN,...,10.0,11.0,11,11,11,11,7.0,40.0,28.0,82.0
3,966005983,Brief,Average,4.6,Large,Spring,o-neck,full,silk,chiffon,...,1812.0,1845.0,1878,1914,1952,1963,1455.0,7213.0,5012.0,14411.0
4,876339541,cute,Low,4.5,Medium,Summer,o-neck,butterfly,chiffonfabric,chiffon,...,1824.0,1919.0,2032,2252,2544,2736,1396.0,7706.0,5678.0,14676.0

In [46]:
# Now Drop the Date columns from inp0 as it is already combined into four seasons.
inp0.drop(inp0.loc[:,'29-08-2013':'10-12-2013'].columns, axis= 1, inplace= True)
inp0.isnull().sum()

Dress_ID            0
Style               0
Price               2
Rating              0
Size                0
Season              2
NeckLine            3
SleeveLength        2
Material          119
FabricType        256
Decoration        224
Pattern Type      102
Recommendation      0
Spring              0
Summer              0
Winter              1
Autumn              2
dtype: int64

Print the null count of inp0 to get the idea about the missing values in data set.

In [47]:
inp0.shape

(479, 17)

In [48]:
# Print the null count of each columns in inp0 dataframe i.e. combined data frame of inp0 and inp1 without date columns.
inp0.isnull().sum()

Dress_ID            0
Style               0
Price               2
Rating              0
Size                0
Season              2
NeckLine            3
SleeveLength        2
Material          119
FabricType        256
Decoration        224
Pattern Type      102
Recommendation      0
Spring              0
Summer              0
Winter              1
Autumn              2
dtype: int64

You can see that there are two types of variables one with a large number of missing values and another is very less number of missing values. These two columns can be categorized as:

Type-1: Missing values are very less (around 2 or 3 missing values): Price, Season, NeckLine, SleeveLength, Winter and Autumn. 

Type-2: Missing values are large in numbers (more than 15%): Material, FabricType, Decoration and Pattern Type.

In [49]:
# Deal with the missing values of Type-1 columns: Price, Season, NeckLine, SleeveLength, Winter and Autumn.
inp0 = inp0[~(inp0['Price'].isnull())]
inp0 = inp0[~(inp0['Season'].isnull())]
inp0 = inp0[~(inp0['NeckLine'].isnull())]
inp0 = inp0[~(inp0['SleeveLength'].isnull())]
inp0 = inp0[~(inp0['Winter'].isnull())]
inp0 = inp0[~(inp0['Autumn'].isnull())]

In [163]:
print(inp0.shape)
inp0.isnull().sum()

(471, 17)

Dress_ID            0
Style               0
Price               0
Rating              0
Size                0
Season              0
NeckLine            0
SleeveLength        0
Material          116
FabricType        250
Decoration        220
Pattern Type       98
Recommendation      0
Spring              0
Summer              0
Winter              0
Autumn              0
dtype: int64

In [ ]:
# Deal with the missing values for Type-2 columns: Material, FabricType, Decoration and Pattern Type.

### Standardise value

In the given dataset, there are certain discrepancies with the categorical names such as irregular spellings. Choose the correct option of columns with irregular categories and update them.
 
- Season, NeckLine
- Price, Material
- fabricType, Decoration
- Season, SleeveLength

In [50]:
#correcting the spellings.
inp0.Season= inp0.Season.replace('Automn', "Autumn")

inp0.Season= inp0.Season.replace('spring', "Spring")

inp0.Season= inp0.Season.replace('winter', "Winter")

In [51]:
inp0['Season'].value_counts()

Season
Summer    151
Winter    136
Spring    118
Autumn     66
Name: count, dtype: int64

In [52]:
#correcting the Spellings.
inp0['SleeveLength'].value_counts()

SleeveLength
sleevless         213
short              92
full               91
halfsleeve         32
threequarter       17
thressqatar         8
sleeveless          4
capsleeves          3
sleeevless          2
cap-sleeves         2
urndowncollor       1
half                1
turndowncollor      1
threequater         1
Petal               1
butterfly           1
sleveless           1
Name: count, dtype: int64

In [53]:
inp0.SleeveLength = inp0.SleeveLength.replace('sleevless', "sleeveless")
inp0.SleeveLength = inp0.SleeveLength.replace('sleeevless', "sleeveless")
inp0.SleeveLength = inp0.SleeveLength.replace('sleveless', "sleeveless")

inp0.SleeveLength = inp0.SleeveLength.replace('thressqatar', "threequarter")
inp0.SleeveLength = inp0.SleeveLength.replace('threequater', "threequarter")

inp0.SleeveLength = inp0.SleeveLength.replace('cap-sleeves', "capsleeves")

inp0.SleeveLength = inp0.SleeveLength.replace('urndowncollor', "turndowncollor")

In [54]:
inp0['SleeveLength'].value_counts()

SleeveLength
sleeveless        220
short              92
full               91
halfsleeve         32
threequarter       26
capsleeves          5
turndowncollor      2
Petal               1
butterfly           1
half                1
Name: count, dtype: int64

## Univariate Analysis

### Categorical Unordered Univariate Analysis

There is a column named ‘Style’ in ‘Attribute Dataset’ which consists of the different style categories of the women apparels. Certain categories whose total sale is less than 50000 across all the seasons is considered under one single category as ‘Others’.

Which of the following categories in ‘Style’ column can be grouped into ‘Others’ category? and perform the grouping operation in the notebook for further analysis.
- Flare, fashion
- Novelty, bohemian
- OL, fashion, work
- Novelty, fashion, Flare

In [55]:
inp0.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,Material,FabricType,Decoration,Pattern Type,Recommendation,Spring,Summer,Winter,Autumn
0,1006032852,Sexy,Low,4.6,Medium,Summer,o-neck,sleeveless,NaN,chiffon,ruffles,animal,1,2660.0,13899.0,9658.0,26857.0
1,1212192089,Casual,Low,0.0,Large,Summer,o-neck,Petal,microfiber,NaN,ruffles,animal,0,750.0,6216.0,6405.0,17311.0
2,1190380701,vintage,High,0.0,Large,Autumn,o-neck,full,polyster,NaN,NaN,print,0,7.0,40.0,28.0,82.0
3,966005983,Brief,Average,4.6,Large,Spring,o-neck,full,silk,chiffon,embroidary,print,1,1455.0,7213.0,5012.0,14411.0
4,876339541,cute,Low,4.5,Medium,Summer,o-neck,butterfly,chiffonfabric,chiffon,bow,dot,0,1396.0,7706.0,5678.0,14676.0

In [56]:
# Group "Style" categories into "Others" which have less than 50000 sales across all the seasons.
inp0['Total_sales']=inp0['Summer']+inp0['Winter']+inp0['Autumn']+inp0['Spring']

In [57]:
style_grouped=inp0.groupby(['Style'])
style_grouped['Total_sales'].sum()

Style
Brief        139628.0
Casual      1103558.0
Flare          2089.0
Novelty       13286.0
OL              289.0
Sexy         452355.0
bohemian      69117.0
cute         361999.0
fashion         395.0
party        142041.0
sexy          77443.0
vintage      180574.0
work          93095.0
Name: Total_sales, dtype: float64

What is the percentage of “cute” and “Others” category in “Style” column in “Attribute DataSet” respectively?
- 46%, 5%
- 9%, 2.1%
- 2.1%, 5%
- 13.8%, 9%

In [58]:
inp0['Style']=inp0['Style'].apply(lambda x:'Others' if style_grouped.get_group(x)['Total_sales'].sum() < 50000 else x)

In [59]:
# Calculate the percentage of each categories in the "Style" variable.
inp0.Style.value_counts()

Style
Casual      217
Sexy         65
party        48
cute         43
vintage      25
bohemian     23
Brief        17
work         17
Others       10
sexy          6
Name: count, dtype: int64

In [60]:
inp0['Style'].value_counts(normalize=True)*100

Style
Casual      46.072187
Sexy        13.800425
party       10.191083
cute         9.129512
vintage      5.307856
bohemian     4.883227
Brief        3.609342
work         3.609342
Others       2.123142
sexy         1.273885
Name: proportion, dtype: float64

Similarly Club Neckline, SLeeve length categories into "Others" which have less than 50000 sales across all the seasons.

In [61]:
# Group "Neckline" categories into "Others" which have less than 50000 sales across all the seasons.
Neckline_grouped=inp0.groupby(['NeckLine'])
inp0['NeckLine']=inp0['NeckLine'].apply(lambda x:'Others' if Neckline_grouped.get_group(x)['Total_sales'].sum()<50000 else x)

In [62]:
# Group "Sleeve length" categories into "Others" which have less than 50000 sales across all the seasons.
SleeveLength_grouped=inp0.groupby(['SleeveLength'])
SleeveLength_grouped['Total_sales'].sum()

SleeveLength
Petal              30682.0
butterfly          29456.0
capsleeves         13603.0
full              455494.0
half                 373.0
halfsleeve        207470.0
short             696130.0
sleeveless        965535.0
threequarter      233543.0
turndowncollor      3583.0
Name: Total_sales, dtype: float64

Club material, fabrictype, patterntype and decoration categories into "Others" which have less than 25000 sales across all the seasons

In [63]:
# Group "material" categories into "Others" which have less than 25000 sales across all the seasons.
Material_grouped=inp0.groupby(['Material'])
inp0['Material']=inp0['Material'].apply(lambda x:'Others' if Material_grouped.get_group(x)['Total_sales'].sum()<25000 else x)

KeyError: nan

In [192]:
# Group "fabric type" categories into "Others" which have less than 25000 sales across all the seasons.
fabric_grouped=inp0.groupby(['FabricType'])
inp0['FabricType']=inp0['FabricType'].apply(lambda x:'Others' if fabric_grouped.get_group(x)['Total_sales'].sum()<25000 else x)

KeyError: nan

In [193]:
# Group "patern type" categories into "Others" which have less than 25000 sales across all the seasons.
PatternType_grouped=inp0.groupby(['Pattern Type'])
inp0['Pattern Type']=inp0['Pattern Type'].apply(lambda x:'Others' if PatternType_grouped.get_group(x)['Total_sales'].sum()<25000 else x)

KeyError: nan

In [ ]:
# Group "decoration" categories into "Others" which have less than 25000 sales across all the seasons.

### Caregorical Ordered Univariate Analysis

Which of the following is an unordered variable in “Attribute DataSet”.
- Style
- Price
- Season
- Size

### Numerical variable Univariate analysis:

What is the approximate difference between the maximum value and 75th percentile in “Autumn” column.
- Approx 54000
- Approx 55000
- Approx 52000
- Approx 50000

In [ ]:
# Describe the numerical variale: "Autumn".

In [ ]:
# plot the boxplot of "Autumn" column.

Which of the following season has the highest difference between the maximum value and 99th quantile of sales?
- Winter
- Summer
- Spring
- Autumn

In [ ]:
# Find the maximum and 99th percentile of Winter season.

In [ ]:
# Find the maximum and 99th percentile of Summer season.

In [ ]:
# Find the maximum and 99th percentile of Spring season.

In [ ]:
# Find the maximum and 99th percentile of Autumn season.

## Bivariate Analysis

### Numerical- Categorical analysis

Which of the following “Price” category has the lowest average value of rating?
- very-high
- Medium
- Low
- High

In [70]:
inp0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 471 entries, 0 to 478
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Dress_ID        471 non-null    int64
 1   Style           471 non-null    object
 2   Price           471 non-null    object
 3   Rating          471 non-null    float64
 4   Size            471 non-null    object
 5   Season          471 non-null    object
 6   NeckLine        471 non-null    object
 7   SleeveLength    471 non-null    object
 8   Material        355 non-null    object
 9   FabricType      221 non-null    object
 10  Decoration      251 non-null    object
 11  Pattern Type    373 non-null    object
 12  Recommendation  471 non-null    int64
 13  Spring          471 non-null    float64
 14  Summer          471 non-null    float64
 15  Winter          471 non-null    float64
 16  Autumn          471 non-null    float64
 17  Total_sales     471 non-null    float64
dtypes: float64(6), int64(2), object(10)
memory usage: 69.9+ KB

In [73]:
# Find the Mean of Ratings for each Price category.
inp0.groupby(["Price"])['Rating'].mean()

Price
Average      3.454430
High         2.914286
Low          3.731481
Medium       3.156667
very-high    3.123810
Name: Rating, dtype: float64

What is the median of the rating of “vintage” category in Style column?
- 4.6
- 4.7
- 4.55
- 0.00

In [74]:
# Find the median of Ratings for each Style category.
inp0.groupby(["Price"])['Rating'].median()

Price
Average      4.6
High         4.6
Low          4.6
Medium       4.6
very-high    4.6
Name: Rating, dtype: float64

Which of the following season has the highest average value of sale for “Recommendation” value equals to 1.
- Summer
- Spring
- Autumn
- Winter

In [75]:
# Summer sale vs Recommendation.
inp0.groupby(['Recommendation'])['Summer'].mean()

Recommendation
0    1433.547794
1    1469.899497
Name: Summer, dtype: float64

In [76]:
# Spring sale vs Recommendation.
inp0.groupby(['Recommendation'])['Spring'].mean()

Recommendation
0    298.209559
1    303.658291
Name: Spring, dtype: float64

In [77]:
# Autumn sale vs Recommendation.
inp0.groupby(['Recommendation'])['Autumn'].mean()

Recommendation
0    2841.720588
1    2868.060302
Name: Autumn, dtype: float64

In [78]:
# Winter sale vs Recommendation.
inp0.groupby(['Recommendation'])['Winter'].mean()

Recommendation
0     987.654412
1    1002.809045
Name: Winter, dtype: float64

### Categorical categorical bivariate analysis

Which of the following size categories has the highest positive recommendations?
- Medium and extra large
- Extra large and small
- Free and small
- Free and medium

In [79]:
# Size vs Recommendation.
inp0.groupby(['Size'])['Recommendation'].mean()

Size
Extra large    0.285714
Free           0.456790
Large          0.359551
Medium         0.447059
Small          0.361111
Name: Recommendation, dtype: float64

### Multivariate analysis

Which of the following pair of “Style” and “Price” category has the highest average of positive recommendations?
- Price: medium and style: vintage
- Price: medium and style: cute
- Price: very high and style: party
- Price: low and style: sexy

In [80]:
# plot the heat map of Style, price and Recommendation.
res=pd.pivot_table(data=inp0,index='Style',columns='Price',values='Recommendation')
res

Price      Average      High       Low    Medium  very-high
Style
Brief     0.333333       NaN  0.000000       NaN        NaN
Casual    0.345455  0.666667  0.379310  0.666667   0.500000
Others    0.375000       NaN       NaN  0.500000        NaN
Sexy      0.344828  0.000000  0.500000  0.000000   0.000000
bohemian  0.333333       NaN  0.666667  1.000000   1.000000
cute      0.400000  0.666667  0.500000  1.000000        NaN
party     0.647059  0.333333       NaN  0.800000   0.823529
sexy      0.000000       NaN  0.750000  0.000000        NaN
vintage   0.352941  0.000000  0.250000  0.500000        NaN
work      0.214286       NaN  0.000000  0.000000        NaN

Which of the following material type has no recommendation in summer and winter seasons?
- Mix and Milksilk
- Nylon and Rayon
- Microfiber and Silk
- Milksilk and Microfiber

In [81]:
# plot the heat map of Season, material and Recommendation.
res1=pd.pivot_table(data=inp0,index='Material',columns='Season',values='Recommendation')
res1

Season           Autumn    Spring    Summer    Winter
Material
acrylic             NaN  0.000000  0.000000  0.000000
cashmere       0.000000       NaN       NaN  1.000000
chiffonfabric  0.500000  0.600000  0.125000  0.000000
cotton         0.294118  0.576923  0.383562  0.500000
lace           0.000000       NaN       NaN       NaN
linen          0.000000       NaN  0.000000       NaN
lycra               NaN  1.000000       NaN  0.000000
microfiber          NaN  1.000000  0.000000  0.000000
milksilk       1.000000       NaN  0.000000  0.000000
mix                 NaN  0.500000  0.333333  0.200000
modal               NaN       NaN  0.000000       NaN
model               NaN       NaN  1.000000       NaN
nylon          0.000000  0.333333  1.000000  0.333333
other               NaN       NaN       NaN  0.000000
polyster       0.266667  0.571429  0.071429  0.346939
rayon          0.666667  1.000000  0.333333       NaN
shiffon             NaN  0.500000       NaN       NaN
silk           0.000000  0.538462  0.000000  0.714286
sill                NaN       NaN  0.000000       NaN
spandex             NaN  0.500000  0.000000       NaN
viscos              NaN       NaN  0.000000  1.000000
wool                NaN       NaN       NaN  0.000000